

import java.sql.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Admin
 */
public class bookticket extends javax.swing.JFrame {

    /**
     * Creates new form frmAddPassanger
     */
    public bookticket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txtpno = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        txtpDOB = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtadd = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtnation = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEid = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtpassno = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtseat = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFlightInfo = new javax.swing.JTable();
        cmbFcode = new javax.swing.JComboBox();
        optDomestic = new javax.swing.JRadioButton();
        optInterI = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        optEco = new javax.swing.JRadioButton();
        optBusi = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtPassengerNm = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        optMale = new javax.swing.JRadioButton();
        optfemale = new javax.swing.JRadioButton();
        btnEdit = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Passenger Details");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel7.setText("Gender :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setText("Passenger No :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 108, -1));

        btnNew.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New.png"))); // NOI18N
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        getContentPane().add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 110, -1));

        btnSave.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 110, -1));

        btnClear.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 80, 40));

        txtpno.setEditable(false);
        txtpno.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        getContentPane().add(txtpno, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 136, -1));

        btnBack.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back copy.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 440, 110, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setText("Flight Code :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 108, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 730, 10));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setText("Date of Birth :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        txtpDOB.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        getContentPane().add(txtpDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 105, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setText("Address :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 70, -1));

        txtadd.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        getContentPane().add(txtadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 344, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setText("Nationality :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 90, -1));

        txtnation.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        getContentPane().add(txtnation, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 344, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel8.setText("Email ID :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 68, -1));

        txtEid.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtEid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEidActionPerformed(evt);
            }
        });
        getContentPane().add(txtEid, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 390, -1));

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel9.setText("Available Seats ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, 110, -1));

        txtpassno.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        getContentPane().add(txtpassno, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 105, -1));

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel10.setText("Seat No :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        txtseat.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        getContentPane().add(txtseat, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 105, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Passanger Details");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, -1));

        tblFlightInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "FlightCode", "FlightName", "Class", "Source", "Destination", "TotalEco", "TotalBusi", "Date", "Departure", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFlightInfo.setOpaque(false);
        jScrollPane1.setViewportView(tblFlightInfo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 720, 180));

        cmbFcode.setModel(new DefaultComboBoxModel());
        cmbFcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFcodeActionPerformed(evt);
            }
        });
        getContentPane().add(cmbFcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 100, 20));

        buttonGroup2.add(optDomestic);
        optDomestic.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        optDomestic.setText("Domestic");
        optDomestic.setOpaque(false);
        getContentPane().add(optDomestic, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, -1, -1));

        buttonGroup2.add(optInterI);
        optInterI.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        optInterI.setText("International");
        optInterI.setOpaque(false);
        getContentPane().add(optInterI, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, -1));

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel11.setText("Passport No. :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 108, -1));

        buttonGroup3.add(optEco);
        optEco.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        optEco.setText("Economic");
        optEco.setOpaque(false);
        getContentPane().add(optEco, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, -1, -1));

        buttonGroup3.add(optBusi);
        optBusi.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        optBusi.setText("Business");
        optBusi.setOpaque(false);
        getContentPane().add(optBusi, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, -1, -1));

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel12.setText("Class :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 60, -1));

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel13.setText("Passanger Name :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        txtPassengerNm.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        getContentPane().add(txtPassengerNm, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 240, -1));

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel14.setText("Select sub Category :");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 150, -1));

        buttonGroup1.add(optMale);
        optMale.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        optMale.setText("Male");
        optMale.setOpaque(false);
        getContentPane().add(optMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        buttonGroup1.add(optfemale);
        optfemale.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        optfemale.setText("Female");
        optfemale.setOpaque(false);
        getContentPane().add(optfemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, -1, -1));

        btnEdit.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Edit copy.png"))); // NOI18N
        btnEdit.setToolTipText("Update");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, 110, -1));

        btnFind.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnFind.setText("Find");
        btnFind.setToolTipText("Search");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });
        getContentPane().add(btnFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, -1, -1));

        btnDelete.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Delete.png"))); // NOI18N
        btnDelete.setToolTipText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 439, 110, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents
Statement stmt=null;
ResultSet rs =null;
String sql ="select * From Passenger";
public void clear(){
    txtEid.setText("");
    txtPassengerNm.setText("");
    txtnation.setText("");
    txtpDOB.setText("");
    txtadd.setText("");
    txtpassno.setText("");
    txtpno.setText("");

}
public void show1()
{
    DefaultTableModel tModel = (DefaultTableModel) tblFlightInfo.getModel();
                int rows = tModel.getRowCount();
                if (rows > 0) {
                    for (int i = 0; i< rows; i++){
                        tModel.removeRow(0);
                    }
                }
       try{

           Class.forName("com.mysql.jdbc.Driver");
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/airlines","root","root");
            stmt=con.createStatement();
           rs=stmt.executeQuery("Select * from Flightdetails");
                    while(rs.next()) {
                       System.out.println(rs.getString(1)+" : "+rs.getString(2));

                String FCode = rs.getString(1);
                String Name=rs.getString(2);
                String cls=rs.getString(3);
                String source=rs.getString(4);
                String desti=rs.getString(5);
                String Eco=rs.getString(6);
                String Busi=rs.getString(7);
                String Date=rs.getString(8);
                String Depart=rs.getString(9);
                String Price=rs.getString(10);
                tModel.addRow(new Object[] {FCode,Name,cls,source,desti,  Eco,Busi,Date,Depart,Price});
                    }
                } catch (Exception e){
                    JOptionPane.showMessageDialog(this, e.getMessage());

                }
}
    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        try{
         Class.forName("com.mysql.jdbc.Driver");
         Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/airlines","root","root");
         stmt=con.createStatement();
         rs=stmt.executeQuery(sql);
         int pno=1244;
         while(rs.next())
         {
             pno=rs.getInt(1);
             System.out.println("Passenger No "+pno);
             pno++;
             System.out.println("Passenger No"+pno);

         }
         txtpno.setText(""+pno);
         con.close();
         rs.close();
         stmt.close();
     }
     catch(Exception e)
     {
JOptionPane.showMessageDialog(this, e.getMessage());
e.printStackTrace();
     }
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
     String upSQL1="";
     try {
    Class.forName("com.mysql.jdbc.Driver");
    Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/airlines","root","root");
        Statement stmt1=null;
        ResultSet rs1=null;
        stmt=con.createStatement();
         rs=stmt.executeQuery("select * from Passenger");
         String cls="";
         String sex="";
         while(rs.next())
         {
                System.out.println(rs.getString(1)+" : "+rs.getString(2));

         }
             String fcode=(String)cmbFcode.getSelectedItem();
             int pno=Integer.parseInt(txtpno.getText());
             String name=txtPassengerNm.getText();
             String dob=txtpDOB.getText();
             String adrss=txtadd.getText();
             String nation=txtnation.getText();
             if(optfemale.isSelected()) {sex="F";}
             if(optMale.isSelected()) {sex="M";}
             String eid=txtEid.getText();
            int pprtno=Integer.parseInt(txtpno.getText());
            int seatno=Integer.parseInt(txtseat.getText());
            String SubCate="";
            if(optDomestic.isSelected()) SubCate="Domes";
            if(optInterI.isSelected()) SubCate="Inter";
            if(optBusi.isSelected()) cls="Busi";
            if(optEco.isSelected()) cls="Eco";
 System.out.println("INSERT INTO Passenger VALUES ('"+(pno)+"','"+(fcode)+"','"+(name)+"','"+(sex)+"','"+(dob)+"','" +(adrss)+"','"+(nation)+"','"+(eid)+"','"+(pprtno)+"','"+(seatno)+"')");
 String strSQL="INSERT INTO Passenger VALUES ('"+(pno)+"','"+(fcode)+"','"+(name)+"','"+(sex)+"','"+(dob)+"','" +(adrss)+"','"+(nation)+"','"+(eid)+"','"+(pprtno)+"','"+(seatno)+"','"+(SubCate)+"','"+(cls)+"')";
 int rowEffected=stmt.executeUpdate(strSQL);
           System.out.println("rows Effected :"+rowEffected);
             System.out.println(strSQL);
           JOptionPane.showMessageDialog(this, "Saved Record", " int rowSave",-1);
    /**********update flight seat***********/
                 stmt1 = con.createStatement();
                rs1 = stmt1.executeQuery("select * from flightdetails");

                while (rs1.next())
                {
                     fcode=rs1.getString(1);
                }

                 fcode=(String)cmbFcode.getSelectedItem();
                stmt1 = con.createStatement();
                rs1 = stmt1.executeQuery("select * from flightdetails");
                if(optBusi.isSelected()){
                   upSQL1="Update Flightdetails set totalBus=totalBus-1 Where Flightcode='"+fcode+"'";

                }
                if(optEco.isSelected()){
                   upSQL1="Update Flightdetails set totalEco=totalEco-1 Where Flightcode='"+fcode+"'";
                }
            System.out.println(upSQL1);
            int rowsEffected1=stmt1.executeUpdate(upSQL1);
            if(rowsEffected1==0)
                JOptionPane.showMessageDialog(this,"Record does not exists");
            else
                JOptionPane.showMessageDialog(this,"Product Record Updated");
            System.out.println(rowsEffected1+"rows effected");
            }
    catch(Exception e)
    {
JOptionPane.showMessageDialog(this, e.getMessage());
e.printStackTrace();
    }//GEN-LAST:event_btnSaveActionPerformed

    }
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
       clear();

    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.setVisible(false);
        new frmMain().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
       String sql1="Select * from FlightDetails";
        try{

            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/airlines","root","root");
            stmt=con.createStatement();
            rs=stmt.executeQuery(sql1);
            DefaultTableModel tModel=(DefaultTableModel) tblFlightInfo.getModel();
            DefaultComboBoxModel model=(DefaultComboBoxModel) cmbFcode.getModel();
            while(rs.next()) {
                model.addElement(rs.getString(1));
           }
      }
      catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }

show1();
    }//GEN-LAST:event_formWindowGainedFocus

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
      //  comFcode.setEditable(false);
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/airlines","root","root");
            stmt=con.createStatement();
            rs=stmt.executeQuery(sql);
            String cls="";
            String sex="";
            //  while(rs.next()){

             String fcode=(String)cmbFcode.getSelectedItem();
             int pno=Integer.parseInt(txtpno.getText());
             String name=txtPassengerNm.getText();
             String dob=txtpDOB.getText();
             String adrss=txtadd.getText();
             String nation=txtnation.getText();
             if(optfemale.isSelected()) {sex="F";}
             if(optMale.isSelected()) {sex="M";}
             String eid=txtEid.getText();
            int pprtno=Integer.parseInt(txtpno.getText());
            int seatno=Integer.parseInt(txtseat.getText());
            String SubCate="";
            if(optDomestic.isSelected()) SubCate="Domes";
            if(optInterI.isSelected()) SubCate="Inter";
            if(optBusi.isSelected()) cls="Busi";
            if(optEco.isSelected()) cls="Eco";
            String strSQL="Update Passenger set name='"+(name)+"', gender='"+(sex)+"', dob='"+(dob)+"',address='"+(adrss)+"',nationality='"+(nation)+"', emailId='"+(eid)+"', FlightCode='"+(fcode)+"',SeatNo='"+(seatno)+"', SubCate='"+(SubCate)+"', class='"+(cls)+"' Where PassengerNo="+pno;

            System.out.println(strSQL);
            int rowsEffected=stmt.executeUpdate(strSQL);
            if(rowsEffected==0)
                JOptionPane.showMessageDialog(this,"Record does not exists");
            else
                JOptionPane.showMessageDialog(this,"Product Record Updated");
            System.out.println(rowsEffected+"rows effected");

            con.close();

        } catch(Exception e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
            e.printStackTrace();
        }
}//GEN-LAST:event_btnEditActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        btnNew.setEnabled(false);
        btnDelete.setEnabled(true);
        btnEdit.setEnabled(true);
        btnSave.setEnabled(false);
        boolean r;
        String find="";
        try{

            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/airlines","root","root");
            find=JOptionPane.showInputDialog(this, "Enter the Passenger Code", "Search", JOptionPane.OK_CANCEL_OPTION);

            String SQL1="Select * from Passenger where PassengerNo='"+(find)+"'";
            System.out.println(SQL1);

            stmt = con.createStatement();
            rs = stmt.executeQuery(SQL1);

            while(rs.next()) {

                String PssgeCode = rs.getString(1);
                String FCode = rs.getString(2);
                String Name=rs.getString(3);
                String Gender=rs.getString(4);
                String dob=rs.getString(5);
                String addrs=rs.getString(6);
                String nationality=rs.getString(7);
                String email=rs.getString(8);
                String PassprtNo=rs.getString(9);
                String Seatno=rs.getString(10);
                String cls=rs.getString(11);
                String SubCate=rs.getString(12);
                if(cls.equals("Inter")) {
                    optInterI.setSelected(true);
                }
                if(cls.equals("Dome")) {
                    optDomestic.setSelected(true);
                }
                //System.out.println(fNo+"|"+fName);
                cmbFcode.setSelectedItem(FCode);
                txtPassengerNm.setText(Name);
                txtadd.setText(addrs);
                txtnation.setText(nationality);
                txtpDOB.setText(dob);
                txtpno.setText(PssgeCode);
                txtseat.setText(Seatno);
                txtpassno.setText(PassprtNo);
                txtEid.setText(email);
                if(SubCate.equals("Eco")) { optEco.setSelected(true); }
                if(SubCate.equals("Busi")) { optEco.setSelected(true); }
            }
            if(cmbFcode.getSelectedItem().equals("")&& txtPassengerNm.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Record Not Found");
            }
            con.close();

        } catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());

        }
}//GEN-LAST:event_btnFindActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/airlines","root","root");
            System.out.println(1);
            // String SQL="Select * from flightdetails";
            stmt = con.createStatement();
            rs = stmt.executeQuery(sql);
            int response= JOptionPane.showConfirmDialog(this, "Are you sure You want to delete Record?", "Delete Comfirmation", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.NO_OPTION)
                System.out.println("No button clicked");
            else if (response == JOptionPane.YES_OPTION) {
                System.out.println("Yes button clicked");
                String strSQL="Delete from Passenger where PassengerNo='"+txtpno.getText()+"'";
                int rowEffected=stmt.executeUpdate(strSQL);
                System.out.println("rowEffected="+rowEffected);
                if (rowEffected == 0) {
                    JOptionPane.showMessageDialog(this,"Record Not Deleted");
                } else {
                    JOptionPane.showMessageDialog(this,"Record  Deleted");
                    clear();
                }
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
}//GEN-LAST:event_btnDeleteActionPerformed

    private void cmbFcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFcodeActionPerformed
       txtEid.setEnabled(true);
    txtPassengerNm.setText("");
    txtnation.setText("");
    txtpDOB.setText("");
    txtadd.setText("");
    txtpassno.setText("");
    txtpno.setText("");
    }//GEN-LAST:event_cmbFcodeActionPerformed

    private void txtEidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEidActionPerformed
        setEnabled(false);
    }//GEN-LAST:event_txtEidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAddPassanger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAddPassanger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAddPassanger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAddPassanger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAddPassanger().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox cmbFcode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton optBusi;
    private javax.swing.JRadioButton optDomestic;
    private javax.swing.JRadioButton optEco;
    private javax.swing.JRadioButton optInterI;
    private javax.swing.JRadioButton optMale;
    private javax.swing.JRadioButton optfemale;
    private javax.swing.JTable tblFlightInfo;
    private javax.swing.JTextField txtEid;
    private javax.swing.JTextField txtPassengerNm;
    private javax.swing.JTextField txtadd;
    private javax.swing.JTextField txtnation;
    private javax.swing.JTextField txtpDOB;
    private javax.swing.JTextField txtpassno;
    private javax.swing.JTextField txtpno;
    private javax.swing.JTextField txtseat;
    // End of variables declaration//GEN-END:variables
}
