

import java.sql.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Admin
 */
public class frmAddPassanger extends javax.swing.JFrame {
    int num;
    /**
     * Creates new form frmAddPassanger
     */
    //int numberrrrr=Integer.parseInt(txtnoofseats.getText());
    public frmAddPassanger() {
        initComponents();
        btnDelete.setVisible(false);
        user.setVisible(false);
        txtuser.setVisible(false);
        txtnoofseats.setVisible(false);
        txtfname.setVisible(false);
        jLabel17.setVisible(false);
        txtfcode.setEditable(false);
        txtpno.setEditable(false);
        txtsrc.setEditable(false);
        txtdes.setEditable(false);
        btnNew.setVisible(false);
        btnDelete.setVisible(false);
        btnBack.setVisible(false);
        //num=Integer.parseInt(txtnoofseats.getText());
    }
    public void setf(String f) {
        txtfcode.setText(f);
    }
    public void setp(String f) {
        txtpno.setText(f);
    }
    public void sets(String f) {
        txtsrc.setText(f);
    }
    public void setd(String f) {
        txtdes.setText(f);
    }
    public void setu(String f) {
        txtuser.setText(f);
    }
    public void setfmame(String f) {
        txtfname.setText(f);
    }
    public void setno(String f) {
       // String s=Integer.parseInt(f);
        txtnoofseats.setText(f);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txtpno = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        txtpDOB = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtadd = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtnation = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEid = new javax.swing.JTextField();
        txtpassno = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtseat = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        optDomestic = new javax.swing.JRadioButton();
        optInterI = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        optEco = new javax.swing.JRadioButton();
        optBusi = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtPassengerNm = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        optMale = new javax.swing.JRadioButton();
        optfemale = new javax.swing.JRadioButton();
        btnDelete = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtfcode = new javax.swing.JTextField();
        txtdes = new javax.swing.JTextField();
        txtsrc = new javax.swing.JTextField();
        txtuser = new javax.swing.JTextField();
        user = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        txtnoofseats = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jMenuBar8 = new javax.swing.JMenuBar();
        home7 = new javax.swing.JMenu();
        search = new javax.swing.JMenu();
        food = new javax.swing.JMenu();
        about = new javax.swing.JMenu();
        flyers = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        admin = new javax.swing.JMenu();
        exit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Passenger Details");
        setPreferredSize(new java.awt.Dimension(1470, 770));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 51));
        jLabel7.setText("Gender :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, 30));

        jLabel2.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setText("Passenger No :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 190, 30));

        btnNew.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New.png"))); // NOI18N
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        getContentPane().add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 590, 110, -1));

        btnSave.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        btnSave.setForeground(new java.awt.Color(51, 0, 153));
        btnSave.setText("Book");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 570, 160, 50));

        btnClear.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        btnClear.setForeground(new java.awt.Color(51, 0, 153));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 570, 170, 50));

        txtpno.setEditable(false);
        txtpno.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        getContentPane().add(txtpno, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 136, -1));

        btnBack.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back copy.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 590, 110, -1));

        jLabel3.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Flight Code :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 31, 180, 30));

        jSeparator1.setPreferredSize(new java.awt.Dimension(0, 4));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 556, 800, 10));

        jLabel4.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 51));
        jLabel4.setText("Date of Birth :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, 30));

        txtpDOB.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        getContentPane().add(txtpDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 140, -1));

        jLabel5.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 51));
        jLabel5.setText("Address :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 120, 30));

        txtadd.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        getContentPane().add(txtadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 360, -1));

        jLabel6.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 51));
        jLabel6.setText("Nationality :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 140, 30));

        txtnation.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        txtnation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnationActionPerformed(evt);
            }
        });
        getContentPane().add(txtnation, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 140, -1));

        jLabel8.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 51));
        jLabel8.setText("Email ID :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 130, 30));

        txtEid.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        getContentPane().add(txtEid, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 360, -1));

        txtpassno.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        txtpassno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassnoActionPerformed(evt);
            }
        });
        getContentPane().add(txtpassno, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 210, -1));

        jLabel10.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 51));
        jLabel10.setText("Seat No :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 90, 30));

        txtseat.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        getContentPane().add(txtseat, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 130, 30));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Passenger Details");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1460, -1));

        buttonGroup2.add(optDomestic);
        optDomestic.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        optDomestic.setForeground(new java.awt.Color(255, 255, 51));
        optDomestic.setText("Domestic");
        optDomestic.setOpaque(false);
        getContentPane().add(optDomestic, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, -1, -1));

        buttonGroup2.add(optInterI);
        optInterI.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        optInterI.setForeground(new java.awt.Color(255, 255, 51));
        optInterI.setText("International");
        optInterI.setOpaque(false);
        getContentPane().add(optInterI, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, -1, -1));

        jLabel11.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 51));
        jLabel11.setText("Passport No. :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 150, 30));

        buttonGroup3.add(optEco);
        optEco.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        optEco.setForeground(new java.awt.Color(255, 255, 0));
        optEco.setText("Economic");
        optEco.setOpaque(false);
        getContentPane().add(optEco, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, -1, 30));

        buttonGroup3.add(optBusi);
        optBusi.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        optBusi.setForeground(new java.awt.Color(255, 255, 0));
        optBusi.setText("Business");
        optBusi.setOpaque(false);
        optBusi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optBusiActionPerformed(evt);
            }
        });
        getContentPane().add(optBusi, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, -1, 30));

        jLabel12.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 51));
        jLabel12.setText("Class :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 100, 30));

        jLabel13.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 51));
        jLabel13.setText("Passenger Name :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, 30));

        txtPassengerNm.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        getContentPane().add(txtPassengerNm, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 260, -1));

        jLabel14.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 51));
        jLabel14.setText("Select sub Category :");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 210, 30));

        buttonGroup1.add(optMale);
        optMale.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        optMale.setForeground(new java.awt.Color(255, 255, 51));
        optMale.setText("Male");
        optMale.setOpaque(false);
        getContentPane().add(optMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, -1, -1));

        buttonGroup1.add(optfemale);
        optfemale.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        optfemale.setForeground(new java.awt.Color(255, 255, 51));
        optfemale.setText("Female");
        optfemale.setOpaque(false);
        getContentPane().add(optfemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, -1, -1));

        btnDelete.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Delete.png"))); // NOI18N
        btnDelete.setToolTipText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 590, 110, 40));

        jLabel15.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 51));
        jLabel15.setText("Source:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 60, 90, 30));

        jLabel16.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 51));
        jLabel16.setText("Destination:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 100, 130, 30));

        txtfcode.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        getContentPane().add(txtfcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 130, -1));

        txtdes.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        txtdes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdesActionPerformed(evt);
            }
        });
        getContentPane().add(txtdes, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 100, 220, -1));

        txtsrc.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        txtsrc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsrcActionPerformed(evt);
            }
        });
        getContentPane().add(txtsrc, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 60, 220, -1));

        txtuser.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        txtuser.setForeground(new java.awt.Color(255, 255, 51));
        getContentPane().add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 230, 180, -1));

        user.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 51));
        user.setText("Username");
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 220, 110, 30));

        jLabel17.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 51));
        jLabel17.setText("Flightname");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 150, 130, 30));

        txtfname.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        txtfname.setForeground(new java.awt.Color(255, 255, 51));
        getContentPane().add(txtfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 150, 260, -1));

        jLabel18.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 51));
        jLabel18.setText("Status");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 80, 30));

        buttonGroup4.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jRadioButton1.setText("Confirm");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, 110, 30));

        txtnoofseats.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        txtnoofseats.setForeground(new java.awt.Color(255, 255, 51));
        getContentPane().add(txtnoofseats, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 300, 190, -1));

        jLabel19.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 51));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/china-airlines.jpg"))); // NOI18N
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1470, 790));

        jMenuBar8.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar8.setAlignmentX(20.0F);
        jMenuBar8.setPreferredSize(new java.awt.Dimension(301, 49));

        home7.setText("HOME");
        home7.setAlignmentX(205.0F);
        home7.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        home7.setIconTextGap(30);
        home7.setMaximumSize(new java.awt.Dimension(205, 32767));
        home7.setPreferredSize(new java.awt.Dimension(205, 21));
        home7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        jMenuBar8.add(home7);

        search.setText("SEARCH");
        search.setAlignmentX(205.0F);
        search.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        search.setIconTextGap(30);
        search.setPreferredSize(new java.awt.Dimension(205, 21));
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
        });
        jMenuBar8.add(search);

        food.setText("FOOD MENU");
        food.setAlignmentX(415.0F);
        food.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        food.setIconTextGap(30);
        food.setMaximumSize(new java.awt.Dimension(255, 32767));
        food.setPreferredSize(new java.awt.Dimension(255, 21));
        food.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                foodMouseClicked(evt);
            }
        });
        jMenuBar8.add(food);

        about.setText("ABOUT");
        about.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        about.setIconTextGap(30);
        about.setPreferredSize(new java.awt.Dimension(205, 21));
        about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutMouseClicked(evt);
            }
        });
        jMenuBar8.add(about);

        flyers.setText("FREQUENT FLYERS");
        flyers.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        flyers.setIconTextGap(30);
        flyers.setMaximumSize(new java.awt.Dimension(255, 32767));
        flyers.setPreferredSize(new java.awt.Dimension(255, 21));
        flyers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flyersMouseClicked(evt);
            }
        });
        jMenuBar8.add(flyers);

        jMenu5.setText("EXIT");
        jMenu5.setAlignmentX(280.0F);
        jMenu5.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jMenu5.setIconTextGap(30);
        jMenu5.setMaximumSize(new java.awt.Dimension(0, 0));
        jMenuBar8.add(jMenu5);

        admin.setText("ADMIN");
        admin.setAlignmentX(0.0F);
        admin.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        admin.setIconTextGap(30);
        admin.setMaximumSize(new java.awt.Dimension(175, 32767));
        admin.setPreferredSize(new java.awt.Dimension(175, 21));
        admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminMouseClicked(evt);
            }
        });
        jMenuBar8.add(admin);

        exit.setText("EXIT");
        exit.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        exit.setMaximumSize(new java.awt.Dimension(175, 32767));
        exit.setPreferredSize(new java.awt.Dimension(175, 21));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jMenuBar8.add(exit);

        setJMenuBar(jMenuBar8);

        pack();
    }// </editor-fold>//GEN-END:initComponents
Statement stmt=null;
ResultSet rs =null;

String sql ="select * From Passenger";
public void clear(){
    txtEid.setText("");
    txtPassengerNm.setText("");
    txtnation.setText("");
    txtpDOB.setText("");
    txtadd.setText("");
    txtpassno.setText("");
    txtpno.setText("");
    txtnoofseats.setText("");
}

/*public void show1()
{DefaultTableModel tModel = (DefaultTableModel) tblFlightInfo.getModel();
                int rows = tModel.getRowCount();
                if (rows > 0) {
                    for (int i = 0; i< rows; i++){
                        tModel.removeRow(0);
                    }
                }
       try{

           Class.forName("com.mysql.jdbc.Driver");
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/airlines","root","root");
            stmt=con.createStatement();
           rs=stmt.executeQuery("Select * from Flightdetails");
                    while(rs.next()) {
                       System.out.println(rs.getString(1)+" : "+rs.getString(2));

                String FCode = rs.getString(1);
                String Name=rs.getString(2);
                String cls=rs.getString(3);
                String source=rs.getString(4);
                String desti=rs.getString(5);
                String Eco=rs.getString(6);
                String Busi=rs.getString(7);
                String Date=rs.getString(8);
                String Depart=rs.getString(9);
                String Price=rs.getString(10);
                tModel.addRow(new Object[] {FCode,Name,cls,source,desti,  Eco,Busi,Date,Depart,Price});
                    }
                } catch (Exception e){
                    JOptionPane.showMessageDialog(this, e.getMessage());

                }
}*/
    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        try{
         Class.forName("com.mysql.jdbc.Driver");
         Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/airlines","root","root");
         stmt=con.createStatement();
         rs=stmt.executeQuery(sql);
         int pno=1244;
         while(rs.next())
         {
             pno=rs.getInt(1);
             System.out.println("Passenger No "+pno);
             pno++;
             System.out.println("Passenger No"+pno);

         }
         txtpno.setText(""+pno);
         con.close();
         rs.close();
         stmt.close();
     }
     catch(Exception e)
     {
JOptionPane.showMessageDialog(this, e.getMessage());
e.printStackTrace();
     }
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
    
    int num=Integer.parseInt(txtnoofseats.getText());
    //num=num-1;
        System.out.println(num);
        if(num!=0) {
        Statement stmt=null;
    ResultSet rs =null;
    try {
    Class.forName("com.mysql.jdbc.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/airlines","root","root");
    stmt=con.createStatement();
    rs=stmt.executeQuery("Select * from Flightdetails");
    String fcod=txtfcode.getText();
    while(rs.next()) {
    String FCode = rs.getString(1);
    if(FCode.equals(fcod)) {
    String Name=rs.getString(2);
    txtfname.setText(Name);
    break;
    }
    }
    } catch (Exception e){
                    JOptionPane.showMessageDialog(this, e.getMessage());

                }
        
        String upSQL1="";
     try {
    Class.forName("com.mysql.jdbc.Driver");
    Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/airlines","root","root");
        Statement stmt1=null;
        ResultSet rs1=null;
        stmt=con.createStatement();
         rs=stmt.executeQuery("select * from Passenger"); //getting next passngr no
         String cls="";
         String sex="";
         String sta="";
         while(rs.next())
         {
                //System.out.println(rs.getString(1)+" : "+rs.getString(2));

         }
             String fcode=txtfcode.getText();
             int pno=Integer.parseInt(txtpno.getText());
             String name=txtPassengerNm.getText();
             String dob=txtpDOB.getText();
             String adrss=txtadd.getText();
             String nation=txtnation.getText();
             if(optfemale.isSelected()) {sex="F";}
             if(optMale.isSelected()) {sex="M";}
             String eid=txtEid.getText();
            int pprtno=Integer.parseInt(txtpno.getText());
            int seatno=Integer.parseInt(txtseat.getText());
            String SubCate="";
            if(optDomestic.isSelected()) SubCate="Domes";
            if(optInterI.isSelected()) SubCate="Inter";
            if(optBusi.isSelected()) cls="Busi";
            if(optEco.isSelected()) cls="Eco";
            if(jRadioButton1.isSelected()) sta="Confirm";
            //if(jRadioButton2.isSelected()) sta="Hold";
            String user=txtuser.getText();
            String fname=txtfname.getText();
            String src=txtsrc.getText();
            String des=txtdes.getText();
            
            
 System.out.println("INSERT INTO Passenger VALUES ('"+(pno)+"','"+(fcode)+"','"+(name)+"','"+(sex)+"','"+(dob)+"','" +(adrss)+"','"+(nation)+"','"+(eid)+"','"+(pprtno)+"','"+(seatno)+"')");
 String strSQL="INSERT INTO Passenger VALUES ('"+(pno)+"','"+(fcode)+"','"+(name)+"','"+(sex)+"','"+(dob)+"','" +(adrss)+"','"+(nation)+"','"+(eid)+"','"+(pprtno)+"','"+(seatno)+"','"+(SubCate)+"','"+(cls)+"')";
 String strSQL1="INSERT INTO custdetails VALUES ('"+(user)+"','"+(fcode)+"','"+(fname)+"','"+(sta)+"','"+(name)+"','"+(sex)+"','" +(dob)+"','"+(eid)+"','"+(src)+"','"+(des)+"','"+(pno)+"','"+(seatno)+"','"+(cls)+"','"+(SubCate)+"')";
 int rowEffected=stmt.executeUpdate(strSQL);
 int rowEffected1=stmt.executeUpdate(strSQL1);
            
 
           System.out.println("rows Effected :"+rowEffected);
             System.out.println(strSQL);
          // JOptionPane.showMessageDialog(this, "Saved Record", " int rowSave",-1);
    /**********update flight seat***********/
                 stmt1 = con.createStatement();
                rs1 = stmt1.executeQuery("select * from flightdetails");

                while (rs1.next())
                {
                     fcode=rs1.getString(1);
                }

                 fcode=txtfcode.getText();
                stmt1 = con.createStatement();
                rs1 = stmt1.executeQuery("select * from flightdetails");
                if(optBusi.isSelected()){
                   upSQL1="Update Flightdetails set totalBus=totalBus-1 Where Flightcode='"+fcode+"'";

                }
                if(optEco.isSelected()){
                   upSQL1="Update Flightdetails set totalEco=totalEco-1 Where Flightcode='"+fcode+"'";
                }
            System.out.println(upSQL1);
            int rowsEffected1=stmt1.executeUpdate(upSQL1);
            if(rowsEffected1==0)
                JOptionPane.showMessageDialog(this,"Record does not exists");
            //else
               // JOptionPane.showMessageDialog(this,"Product Record Updated");
            System.out.println(rowsEffected1+"rows effected");
            num--;
            JOptionPane.showMessageDialog(rootPane,"Enter details for another ticket","Book another",JOptionPane.INFORMATION_MESSAGE);
            if(num==0) {
                paymoney add=new paymoney();
                add.setu(txtuser.getText());//change it to payment
        add.setVisible(true);
        this.setVisible(false);
            }
            txtnoofseats.setText(""+num);
            clear();
            
            rs=stmt.executeQuery("Select * from passenger");
         int pn=1244;
         while(rs.next())
         {
             pn=rs.getInt(1);
             //System.out.println("Passenger No "+pno);
             pn++;
             //System.out.println("Passenger No"+pno);

         }
         String p=(""+pn);
         txtpno.setText(p);
            
            }
    catch(Exception e)
    {
JOptionPane.showMessageDialog(this, e.getMessage());
e.printStackTrace();
    }//GEN-LAST:event_btnSaveActionPerformed
    } else {
        paymoney add=new paymoney();
add.setu(txtuser.getText());//change it to payment
        add.setVisible(true);
        this.setVisible(false);
        }
    }
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
       clear();

    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.setVisible(false);
        new frmMain().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
       String sql1="Select * from FlightDetails";
        try{

            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/airlines","root","root");
            stmt=con.createStatement();
            rs=stmt.executeQuery(sql1);
            //DefaultTableModel tModel=(DefaultTableModel) tblFlightInfo.getModel();
            /*DefaultComboBoxModel model=(DefaultComboBoxModel) cmbFcode.getModel();
            while(rs.next()) {
                model.addElement(rs.getString(1));
           }*/
      }
      catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }

//show1();
    }//GEN-LAST:event_formWindowGainedFocus

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/airlines","root","root");
            System.out.println(1);
            // String SQL="Select * from flightdetails";
            stmt = con.createStatement();
            rs = stmt.executeQuery(sql);
            int response= JOptionPane.showConfirmDialog(this, "Are you sure You want to delete Record?", "Delete Comfirmation", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.NO_OPTION)
                System.out.println("No button clicked");
            else if (response == JOptionPane.YES_OPTION) {
                System.out.println("Yes button clicked");
                String strSQL="Delete from Passenger where PassengerNo='"+txtpno.getText()+"'";
                int rowEffected=stmt.executeUpdate(strSQL);
                System.out.println("rowEffected="+rowEffected);
                if (rowEffected == 0) {
                    JOptionPane.showMessageDialog(this,"Record Not Deleted");
                } else {
                    JOptionPane.showMessageDialog(this,"Record  Deleted");
                    clear();
                }
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
}//GEN-LAST:event_btnDeleteActionPerformed

    private void txtnationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnationActionPerformed

    private void txtpassnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassnoActionPerformed

    private void optBusiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optBusiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optBusiActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void txtsrcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsrcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsrcActionPerformed

    private void txtdesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdesActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_exitMouseClicked

    private void adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseClicked
        login_admin add = new login_admin();
        add.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_adminMouseClicked

    private void flyersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flyersMouseClicked
        login_customer add = new login_customer();
        add.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_flyersMouseClicked

    private void aboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMouseClicked
        about add = new about();
        add.setVisible(true);
        this.setVisible(false);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutMouseClicked

    private void foodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodMouseClicked
        foodmenu add = new foodmenu();
        add.setVisible(true);
        this.setVisible(false);
             // TODO add your handling code here:
    }//GEN-LAST:event_foodMouseClicked

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked
        searchflights1 add = new searchflights1();
        add.setVisible(true);
        this.setVisible(false);// TODO add your handling code here:*/
    }//GEN-LAST:event_searchMouseClicked

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        login_home1 add = new login_home1();
        add.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAddPassanger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAddPassanger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAddPassanger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAddPassanger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAddPassanger().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu about;
    private javax.swing.JMenu admin;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JMenu exit;
    private javax.swing.JMenu flyers;
    private javax.swing.JMenu food;
    private javax.swing.JMenu home7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton optBusi;
    private javax.swing.JRadioButton optDomestic;
    private javax.swing.JRadioButton optEco;
    private javax.swing.JRadioButton optInterI;
    private javax.swing.JRadioButton optMale;
    private javax.swing.JRadioButton optfemale;
    private javax.swing.JMenu search;
    private javax.swing.JTextField txtEid;
    private javax.swing.JTextField txtPassengerNm;
    private javax.swing.JTextField txtadd;
    private javax.swing.JTextField txtdes;
    private javax.swing.JTextField txtfcode;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtnation;
    private javax.swing.JTextField txtnoofseats;
    private javax.swing.JTextField txtpDOB;
    private javax.swing.JTextField txtpassno;
    private javax.swing.JTextField txtpno;
    private javax.swing.JTextField txtseat;
    private javax.swing.JTextField txtsrc;
    private javax.swing.JTextField txtuser;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
