import java.sql.*;
import javax.swing.JOptionPane;

public class frmupdateflight extends javax.swing.JFrame {

    /**
     * Creates new form frmAddFlightDetail
     */
    public frmupdateflight() {
        initComponents();
        btnClear.setEnabled(false);
        btnEdit.setEnabled(false);
        btnDelete.setEnabled(false);
        txtDepTime.setEnabled(false);
        txtDeptDate.setEnabled(false);
        txtFname.setEnabled(false);
        txtPrice.setEnabled(false);
        txtPrice1.setEnabled(false);
        txtTECo.setEnabled(false);
        txtTotBusi.setEnabled(false);
        txtdes.setEnabled(false);
        txtflightCode.setEnabled(false);
        txtsrc.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        fcode = new javax.swing.JLabel();
        txtflightCode = new javax.swing.JTextField();
        fname = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        source = new javax.swing.JLabel();
        Dest = new javax.swing.JLabel();
        tec = new javax.swing.JLabel();
        txtTECo = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        tbc = new javax.swing.JLabel();
        txtTotBusi = new javax.swing.JTextField();
        cls = new javax.swing.JLabel();
        optDom = new javax.swing.JRadioButton();
        optInter = new javax.swing.JRadioButton();
        Ddate = new javax.swing.JLabel();
        dtime = new javax.swing.JLabel();
        txtDepTime = new javax.swing.JTextField();
        txtDeptDate = new javax.swing.JTextField();
        price = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnFind = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtsrc = new javax.swing.JTextField();
        txtdes = new javax.swing.JTextField();
        price1 = new javax.swing.JLabel();
        txtPrice1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        home = new javax.swing.JMenu();
        search = new javax.swing.JMenu();
        food = new javax.swing.JMenu();
        about = new javax.swing.JMenu();
        flyers = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        admin = new javax.swing.JMenu();
        exit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Flight Detail");
        setBackground(new java.awt.Color(204, 204, 255));
        setPreferredSize(new java.awt.Dimension(1470, 770));
        getContentPane().setLayout(null);

        fcode.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        fcode.setForeground(new java.awt.Color(255, 255, 0));
        fcode.setText("Flight Code :");
        getContentPane().add(fcode);
        fcode.setBounds(100, 80, 120, 21);

        txtflightCode.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        txtflightCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtflightCodeActionPerformed(evt);
            }
        });
        getContentPane().add(txtflightCode);
        txtflightCode.setBounds(390, 70, 136, 27);

        fname.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        fname.setForeground(new java.awt.Color(255, 255, 0));
        fname.setText("Flight Name :");
        getContentPane().add(fname);
        fname.setBounds(100, 130, 129, 21);

        txtFname.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        getContentPane().add(txtFname);
        txtFname.setBounds(390, 120, 230, 30);

        source.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        source.setForeground(new java.awt.Color(255, 255, 0));
        source.setText("Source :");
        getContentPane().add(source);
        source.setBounds(100, 180, 77, 21);

        Dest.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        Dest.setForeground(new java.awt.Color(255, 255, 0));
        Dest.setText("Destination :");
        getContentPane().add(Dest);
        Dest.setBounds(100, 230, 123, 21);

        tec.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        tec.setForeground(new java.awt.Color(255, 255, 0));
        tec.setText("Total Economy Capacity :");
        getContentPane().add(tec);
        tec.setBounds(100, 360, 244, 40);

        txtTECo.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        getContentPane().add(txtTECo);
        txtTECo.setBounds(390, 320, 130, 27);

        btnClear.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        btnClear.setForeground(new java.awt.Color(0, 0, 255));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear);
        btnClear.setBounds(880, 560, 170, 50);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(80, 530, 1310, 10);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Flight Details");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1470, 40);

        tbc.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        tbc.setForeground(new java.awt.Color(255, 255, 0));
        tbc.setText("Total Business Capacity :");
        getContentPane().add(tbc);
        tbc.setBounds(100, 320, 239, 30);

        txtTotBusi.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        getContentPane().add(txtTotBusi);
        txtTotBusi.setBounds(390, 370, 130, 27);

        cls.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        cls.setForeground(new java.awt.Color(255, 255, 0));
        cls.setText("Class :");
        getContentPane().add(cls);
        cls.setBounds(100, 280, 100, 21);

        buttonGroup1.add(optDom);
        optDom.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        optDom.setText("Domestic");
        getContentPane().add(optDom);
        optDom.setBounds(390, 280, 95, 20);

        buttonGroup1.add(optInter);
        optInter.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        optInter.setText("International");
        getContentPane().add(optInter);
        optInter.setBounds(510, 280, 127, 20);

        Ddate.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        Ddate.setForeground(new java.awt.Color(255, 255, 0));
        Ddate.setText("Departure Date :");
        getContentPane().add(Ddate);
        Ddate.setBounds(100, 420, 161, 21);

        dtime.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        dtime.setForeground(new java.awt.Color(255, 255, 0));
        dtime.setText("Departure Time :");
        getContentPane().add(dtime);
        dtime.setBounds(100, 470, 163, 21);

        txtDepTime.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        getContentPane().add(txtDepTime);
        txtDepTime.setBounds(390, 470, 130, 27);

        txtDeptDate.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        txtDeptDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeptDateActionPerformed(evt);
            }
        });
        getContentPane().add(txtDeptDate);
        txtDeptDate.setBounds(390, 420, 127, 27);

        price.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        price.setForeground(new java.awt.Color(255, 255, 0));
        price.setText("Price :");
        getContentPane().add(price);
        price.setBounds(610, 370, 90, 21);

        txtPrice.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        getContentPane().add(txtPrice);
        txtPrice.setBounds(750, 370, 117, 27);

        jButton2.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 204));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1140, 560, 200, 50);

        jLabel2.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("(YYYY-MM-DD)");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(520, 430, 120, 17);

        jLabel3.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("(HH:MM:SS)");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(520, 470, 160, 17);

        btnFind.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        btnFind.setForeground(new java.awt.Color(0, 0, 255));
        btnFind.setText("Find");
        btnFind.setToolTipText("Search");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });
        getContentPane().add(btnFind);
        btnFind.setBounds(110, 560, 170, 50);

        btnEdit.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(0, 0, 255));
        btnEdit.setText("Edit");
        btnEdit.setToolTipText("Update");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit);
        btnEdit.setBounds(360, 560, 170, 50);

        btnDelete.setFont(new java.awt.Font("Showcard Gothic", 1, 36)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(0, 0, 255));
        btnDelete.setText("Delete");
        btnDelete.setToolTipText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);
        btnDelete.setBounds(610, 560, 180, 50);

        txtsrc.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        txtsrc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsrcActionPerformed(evt);
            }
        });
        getContentPane().add(txtsrc);
        txtsrc.setBounds(390, 170, 230, 30);

        txtdes.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        getContentPane().add(txtdes);
        txtdes.setBounds(390, 220, 230, 30);

        price1.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        price1.setForeground(new java.awt.Color(255, 255, 0));
        price1.setText("Price :");
        getContentPane().add(price1);
        price1.setBounds(610, 320, 90, 30);

        txtPrice1.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        getContentPane().add(txtPrice1);
        txtPrice1.setBounds(750, 320, 117, 27);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/china-airlines.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 30, 1460, 780);

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setAlignmentX(20.0F);
        jMenuBar1.setPreferredSize(new java.awt.Dimension(301, 51));

        home.setText("HOME");
        home.setAlignmentX(205.0F);
        home.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        home.setIconTextGap(30);
        home.setMaximumSize(new java.awt.Dimension(205, 32767));
        home.setPreferredSize(new java.awt.Dimension(205, 21));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        jMenuBar1.add(home);

        search.setText("SEARCH");
        search.setAlignmentX(205.0F);
        search.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        search.setIconTextGap(30);
        search.setPreferredSize(new java.awt.Dimension(205, 21));
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
        });
        jMenuBar1.add(search);

        food.setText("FOOD MENU");
        food.setAlignmentX(415.0F);
        food.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        food.setIconTextGap(30);
        food.setMaximumSize(new java.awt.Dimension(255, 32767));
        food.setPreferredSize(new java.awt.Dimension(255, 21));
        food.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                foodMouseClicked(evt);
            }
        });
        jMenuBar1.add(food);

        about.setText("ABOUT");
        about.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        about.setIconTextGap(30);
        about.setPreferredSize(new java.awt.Dimension(205, 21));
        about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutMouseClicked(evt);
            }
        });
        jMenuBar1.add(about);

        flyers.setText("FREQUENT FLYERS");
        flyers.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        flyers.setIconTextGap(30);
        flyers.setMaximumSize(new java.awt.Dimension(255, 32767));
        flyers.setPreferredSize(new java.awt.Dimension(255, 21));
        flyers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flyersMouseClicked(evt);
            }
        });
        jMenuBar1.add(flyers);

        jMenu5.setText("EXIT");
        jMenu5.setAlignmentX(280.0F);
        jMenu5.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jMenu5.setIconTextGap(30);
        jMenu5.setMaximumSize(new java.awt.Dimension(0, 0));
        jMenuBar1.add(jMenu5);

        admin.setText("ADMIN");
        admin.setAlignmentX(0.0F);
        admin.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        admin.setIconTextGap(30);
        admin.setMaximumSize(new java.awt.Dimension(175, 32767));
        admin.setPreferredSize(new java.awt.Dimension(175, 21));
        admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminMouseClicked(evt);
            }
        });
        jMenuBar1.add(admin);

        exit.setText("EXIT");
        exit.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        exit.setMaximumSize(new java.awt.Dimension(175, 32767));
        exit.setPreferredSize(new java.awt.Dimension(175, 21));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jMenuBar1.add(exit);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
Statement stmt=null;
ResultSet rs =null;
String sql ="select * From FlightDetails";
public void clear(){
    txtDepTime.setText("");
    txtDeptDate.setText("");
    txtFname.setText("");
    txtPrice.setText("");
    txtPrice1.setText("");
    txtsrc.setText("");
    txtTECo.setText("");
    txtTotBusi.setText("");
    txtdes.setText("");
    //txtflightCode.setText("");

}

public void uneditable1() {
    btnClear.setEnabled(false);
        btnEdit.setEnabled(false);
        btnDelete.setEnabled(false);
        txtDepTime.setEnabled(false);
        txtDeptDate.setEnabled(false);
        txtFname.setEnabled(false);
        txtPrice.setEnabled(false);
        txtPrice1.setEnabled(false);
        txtTECo.setEnabled(false);
        txtTotBusi.setEnabled(false);
        txtdes.setEnabled(false);
        txtflightCode.setEnabled(false);
        txtsrc.setEnabled(false);
}

public void editable1() {
    btnClear.setEnabled(true);
        btnEdit.setEnabled(true);
        btnDelete.setEnabled(true);
        txtDepTime.setEnabled(true);
        txtDeptDate.setEnabled(true);
        txtFname.setEnabled(true);
        txtPrice.setEnabled(true);
        txtPrice1.setEnabled(true);
        txtTECo.setEnabled(true);
        txtTotBusi.setEnabled(true);
        txtdes.setEnabled(true);
        //txtflightCode.setEnabled(false);
        txtsrc.setEnabled(true);
}
    
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
     clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtDeptDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeptDateActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtDeptDateActionPerformed

    private void txtflightCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtflightCodeActionPerformed
        setEnabled(false);
    }//GEN-LAST:event_txtflightCodeActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        editable1();
        //btnDelete.setEnabled(true);
        //btnEdit.setEnabled(true);
        clear();
        boolean r;
        String find="";
        try{
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/airlines","root","root");
            find=JOptionPane.showInputDialog(this, "Enter the flight Code", "Search", JOptionPane.OK_CANCEL_OPTION);
            
            String SQL1="Select * from flightdetails where Flightcode='"+(find)+"'";
            System.out.println(SQL1);
            
            stmt = con.createStatement();
            rs = stmt.executeQuery(SQL1);
            
            while(rs.next()) {
                
                String fNo = rs.getString(1);
                String fName = rs.getString(2);
                String cls=rs.getString(3);
                String Source=rs.getString(4);
                String Dest=rs.getString(5);
                String totE=rs.getString(6);
                String totB=rs.getString(7);
                String dt=rs.getString(8);
                String tim=rs.getString(9);
                String pric=rs.getString(10);
                String price=rs.getString(11);
                if(cls.equals("International"))
                {
                    optInter.setSelected(true);
                }
                 if(cls.equals("Domestic"))
                {
                    optDom.setSelected(true);
                }
                System.out.println(fNo+"|"+fName);
                txtflightCode.setText(fNo);
                txtFname.setText(fName);
                txtDepTime.setText(tim);
                txtDeptDate.setText(dt);
                txtPrice.setText(pric);
                txtsrc.setText(Source);
                txtTECo.setText(totE);
                txtTotBusi.setText(totB);
                txtdes.setText(Dest);
                txtPrice1.setText(price);
     }
            if(txtflightCode.getText().equals("")&& txtFname.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Oh! flight Not Found","Does not exist", JOptionPane.ERROR_MESSAGE);
            }
            con.close();
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
            
        }
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed

        txtflightCode.setEditable(false);
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/airlines","root","root");
            stmt=con.createStatement();
            rs=stmt.executeQuery(sql);
            //  while(rs.next()){
            String Fcode=txtflightCode.getText().toUpperCase();
            String Fname=txtFname.getText().toUpperCase();
            String Fsource=txtsrc.getText();
            String Desi=txtdes.getText();
            int ftec=Integer.parseInt(txtTECo.getText());
            int ftbc=Integer.parseInt(txtTotBusi.getText());
            String ddat=txtDeptDate.getText();
            String dtim=txtDepTime.getText();
            double fprc=Double.parseDouble(txtPrice.getText());
            double fprc1=Double.parseDouble(txtPrice1.getText());
            String clas="";
            if(optDom.isSelected()){ clas="Domestic";}
             if(optInter.isSelected()){ clas="International";}
             String strSQL="Update Flightdetails set Flightname='"+(Fname)+"', src='"+(Fsource)+"', Destination='"+(Desi)+"',Class='"+(clas)+"',TotalEco='"+(ftec)+"', TotalBus='"+(ftbc)+"',prceco='"+(fprc)+"', fDate='"+(ddat)+"',ftime='"+(dtim)+"', Prcbui='"+(fprc1)+"' Where Flightcode="+Fcode;
            
            System.out.println(strSQL);
            int rowsEffected=stmt.executeUpdate(strSQL);
            if(rowsEffected==0)
                JOptionPane.showMessageDialog(this,"Flight does not exists","Error", JOptionPane.ERROR_MESSAGE);
            else
                JOptionPane.showMessageDialog(this,"Flight details Updated","Successful",JOptionPane.INFORMATION_MESSAGE);
            System.out.println(rowsEffected+"rows effected");
            clear();
            txtflightCode.setText(" ");
            uneditable1();
            con.close();
            
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
            e.printStackTrace();
        }
}//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/airlines","root","root");
            System.out.println(1);
            // String SQL="Select * from flightdetails";
            stmt = con.createStatement();
            rs = stmt.executeQuery(sql);
            int response= JOptionPane.showConfirmDialog(this, "Are you sure You want to delete this flight?", "Delete Comfirmation", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.NO_OPTION)
                System.out.println("No button clicked");
            else if (response == JOptionPane.YES_OPTION) {
                System.out.println("Yes button clicked");
                String strSQL="Delete from flightdetails where Flightcode='"+txtflightCode.getText()+"'";
                int rowEffected=stmt.executeUpdate(strSQL);
                System.out.println("rowEffected="+rowEffected);
                if (rowEffected == 0) {
                    JOptionPane.showMessageDialog(this,"Flight Not Deleted");
                } else {
                    JOptionPane.showMessageDialog(this,"Flight Deleted!!");
                    clear();
                    uneditable1();
                }
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
}//GEN-LAST:event_btnDeleteActionPerformed

    private void txtsrcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsrcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsrcActionPerformed

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        login_home1 add = new login_home1();
        add.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeMouseClicked

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked
        searchflights1 add = new searchflights1();
        add.setVisible(true);
        this.setVisible(false);// TODO add your handling code here:*/
    }//GEN-LAST:event_searchMouseClicked

    private void foodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodMouseClicked
        foodmenu add = new foodmenu();
        add.setVisible(true);
        this.setVisible(false);
                // TODO add your handling code here:
    }//GEN-LAST:event_foodMouseClicked

    private void aboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMouseClicked
        about add = new about();
        add.setVisible(true);
        this.setVisible(false);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutMouseClicked

    private void flyersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flyersMouseClicked
        login_customer add = new login_customer();
        add.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_flyersMouseClicked

    private void adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseClicked
        login_admin add = new login_admin();
        add.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_adminMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_exitMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        login_admin add= new login_admin();
        add.setVisible(true);
        add.back();
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAddFlightDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAddFlightDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAddFlightDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAddFlightDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAddFlightDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ddate;
    private javax.swing.JLabel Dest;
    private javax.swing.JMenu about;
    private javax.swing.JMenu admin;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnFind;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel cls;
    private javax.swing.JLabel dtime;
    private javax.swing.JMenu exit;
    private javax.swing.JLabel fcode;
    private javax.swing.JMenu flyers;
    private javax.swing.JLabel fname;
    private javax.swing.JMenu food;
    private javax.swing.JMenu home;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton optDom;
    private javax.swing.JRadioButton optInter;
    private javax.swing.JLabel price;
    private javax.swing.JLabel price1;
    private javax.swing.JMenu search;
    private javax.swing.JLabel source;
    private javax.swing.JLabel tbc;
    private javax.swing.JLabel tec;
    private javax.swing.JTextField txtDepTime;
    private javax.swing.JTextField txtDeptDate;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtPrice1;
    private javax.swing.JTextField txtTECo;
    private javax.swing.JTextField txtTotBusi;
    private javax.swing.JTextField txtdes;
    private javax.swing.JTextField txtflightCode;
    private javax.swing.JTextField txtsrc;
    // End of variables declaration//GEN-END:variables
}