import java.sql.*;
import javax.swing.JOptionPane;

public class newflight extends javax.swing.JFrame {

    /**
     * Creates new form frmAddFlightDetail
     */
    public newflight() {
        initComponents();
        try{
         Class.forName("com.mysql.jdbc.Driver");
         Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/airlines","root","root");
         stmt=con.createStatement();
         rs=stmt.executeQuery(sql);
         int code=2310;
         while(rs.next())
         {
             code=rs.getInt(1);
             System.out.println("Airline Code "+code);
             code++;
             System.out.println("Airline Code "+code);

         }
         txtflightCode.setText(""+code);
         con.close();
         rs.close();
         stmt.close();
     }
     catch(Exception e)
     {
JOptionPane.showMessageDialog(this, e.getMessage());
e.printStackTrace();
     }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        fcode = new javax.swing.JLabel();
        fname = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        source = new javax.swing.JLabel();
        Dest = new javax.swing.JLabel();
        tec = new javax.swing.JLabel();
        txtTECo = new javax.swing.JTextField();
        btnNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        tbc = new javax.swing.JLabel();
        txtTotBusi = new javax.swing.JTextField();
        cls = new javax.swing.JLabel();
        optDom = new javax.swing.JRadioButton();
        optInter = new javax.swing.JRadioButton();
        Ddate = new javax.swing.JLabel();
        dtime = new javax.swing.JLabel();
        txtDepTime = new javax.swing.JTextField();
        txtDeptDate = new javax.swing.JTextField();
        price = new javax.swing.JLabel();
        txtPrice1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        price1 = new javax.swing.JLabel();
        txtPrice2 = new javax.swing.JTextField();
        txtflightCode = new javax.swing.JLabel();
        txtsrc = new javax.swing.JTextField();
        txtdes = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Flight Detail");
        setBackground(new java.awt.Color(204, 204, 255));

        fcode.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        fcode.setText("Flight Code :");

        fname.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        fname.setText("Flight Name :");

        txtFname.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N

        source.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        source.setText("Source :");

        Dest.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Dest.setText("Destination :");

        tec.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        tec.setText("Total Economy Capacity :");

        txtTECo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N

        btnNew.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Flight Details");
        jLabel1.setOpaque(true);

        tbc.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        tbc.setText("Total Business Capacity :");

        txtTotBusi.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N

        cls.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        cls.setText("Class :");

        buttonGroup1.add(optDom);
        optDom.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        optDom.setText("Domestic");

        buttonGroup1.add(optInter);
        optInter.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        optInter.setText("International");

        Ddate.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Ddate.setText("Daparture Date :");

        dtime.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        dtime.setText("Departure Time :");

        txtDepTime.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N

        txtDeptDate.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtDeptDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeptDateActionPerformed(evt);
            }
        });

        price.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        price.setText("Price for eco :");

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 11)); // NOI18N
        jLabel2.setText("(YYYY-MM-DD)");

        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 11)); // NOI18N
        jLabel3.setText("(HH:MM:SS)");

        price1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        price1.setText("Price for bui :");

        txtflightCode.setText("Click new for new flight code");

        txtdes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnNew)
                        .addGap(93, 93, 93)
                        .addComponent(btnSave)
                        .addGap(54, 54, 54)
                        .addComponent(btnBack)
                        .addGap(34, 34, 34)
                        .addComponent(btnClear))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dtime)
                                    .addComponent(Ddate)
                                    .addComponent(source)
                                    .addComponent(Dest)
                                    .addComponent(tec)
                                    .addComponent(tbc)
                                    .addComponent(cls, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(fcode)
                                        .addComponent(fname))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(price))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(price1)))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrice2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTotBusi, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTECo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(optDom)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(optInter))))
                            .addComponent(txtPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDepTime, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDeptDate, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtflightCode, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtdes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                .addComponent(txtsrc, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtflightCode, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fcode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fname)
                    .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(source)
                    .addComponent(txtsrc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dest)
                    .addComponent(txtdes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(optDom)
                        .addComponent(optInter))
                    .addComponent(cls))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tec)
                    .addComponent(txtTECo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbc)
                    .addComponent(txtTotBusi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ddate)
                    .addComponent(txtDeptDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dtime)
                    .addComponent(txtDepTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price)
                    .addComponent(txtPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price1)
                    .addComponent(txtPrice2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNew)
                    .addComponent(btnSave)
                    .addComponent(btnBack)
                    .addComponent(btnClear))
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
Statement stmt=null;
ResultSet rs =null;
String sql ="select * From FlightDetails";
public void clear(){
    txtDepTime.setText("");
    txtDeptDate.setText("");
    txtFname.setText("");
    txtPrice1.setText("");
    txtPrice2.setText("");
    txtsrc.setText("");
    txtTECo.setText("");
    txtTotBusi.setText("");
    txtdes.setText("");
    txtflightCode.setText("");

}
    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
    //txtflightCode.setEditable(false);
        try{
         Class.forName("com.mysql.jdbc.Driver");
         Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/airlines","root","root");
         stmt=con.createStatement();
         rs=stmt.executeQuery(sql);
         int code=2310;
         while(rs.next())
         {
             code=rs.getInt(1);
             System.out.println("Airline Code "+code);
             code++;
             System.out.println("Airline Code "+code);

         }
         txtflightCode.setText(""+code);
         con.close();
         rs.close();
         stmt.close();
     }
     catch(Exception e)
     {
JOptionPane.showMessageDialog(this, e.getMessage());
e.printStackTrace();
     }
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
try {
    Class.forName("com.mysql.jdbc.Driver");
    Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/airlines","root","root");
         stmt=con.createStatement();
         rs=stmt.executeQuery("select * from FlightDEtails");
         String cls="";
         while(rs.next())
         {
                System.out.println(rs.getString(1)+" : "+rs.getString(2));

         }
             int code=Integer.parseInt(txtflightCode.getText());
             String name=txtFname.getText();
             if(optDom.isSelected()){ cls="Domestic";}
             if(optDom.isSelected()){ cls="International";}
             //String src=txtSource.getText();
             String src=txtsrc.getText();
             
             String dst=(String) txtdes.getText();
            int Te=Integer.parseInt(txtTECo.getText());
            int Tb=Integer.parseInt(txtTotBusi.getText());
            double prceco =Double.parseDouble(txtPrice1.getText());
            double prcbui =Double.parseDouble(txtPrice2.getText());
            String dt=txtDeptDate.getText();
            String dTime=txtDepTime.getText();

 String strSQL="INSERT INTO FlightDetails VALUES ('"+(code)+"','"+(name)+"','"+(cls)+"','"+(src)+"','"+(dst)+"','"+(Te)+"','"+(Tb)+"','"+(dt)+"','"+(dTime)+"','"+(prceco)+"','"+(prcbui)+"')";
             int rowEffected=stmt.executeUpdate(strSQL);
           System.out.println("rows Effected :"+rowEffected);
           System.out.println(strSQL);
           JOptionPane.showMessageDialog(this, "Saved Record", " int rowSave",-1);
} catch(Exception e)
     {
JOptionPane.showMessageDialog(this, e.getMessage());
e.printStackTrace();
    }//GEN-LAST:event_btnSaveActionPerformed

    }
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
     clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.setVisible(false);
        new frmMain().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtDeptDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeptDateActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtDeptDateActionPerformed

    private void txtdesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAddFlightDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAddFlightDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAddFlightDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAddFlightDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAddFlightDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ddate;
    private javax.swing.JLabel Dest;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel cls;
    private javax.swing.JLabel dtime;
    private javax.swing.JLabel fcode;
    private javax.swing.JLabel fname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton optDom;
    private javax.swing.JRadioButton optInter;
    private javax.swing.JLabel price;
    private javax.swing.JLabel price1;
    private javax.swing.JLabel source;
    private javax.swing.JLabel tbc;
    private javax.swing.JLabel tec;
    private javax.swing.JTextField txtDepTime;
    private javax.swing.JTextField txtDeptDate;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtPrice1;
    private javax.swing.JTextField txtPrice2;
    private javax.swing.JTextField txtTECo;
    private javax.swing.JTextField txtTotBusi;
    private javax.swing.JTextField txtdes;
    private javax.swing.JLabel txtflightCode;
    private javax.swing.JTextField txtsrc;
    // End of variables declaration//GEN-END:variables
}
