/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on Nov 18, 2015, 9:06:23 AM
 */

/**
 *
 * @author ADMIN
 */
public class NewJFrame extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();
        /*jButton1.setOpaque(false);
jButton1.setContentAreaFilled(false);
jButton1.setBorderPainted(false);*/
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1470, 770));
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Perpetua Titling MT", 3, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("CLICK HERE TO START FLYING");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(470, 170, 490, 40);

        jLabel1.setFont(new java.awt.Font("Lucida Console", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inltair_26oct16.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1300, 400));
        jLabel1.setMinimumSize(new java.awt.Dimension(1300, 400));
        jLabel1.setPreferredSize(new java.awt.Dimension(1300, 400));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 240, 1300, 380);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo2.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setAlignmentY(0.0F);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, -20, 390, 160);

        jLabel7.setFont(new java.awt.Font("Segoe Script", 3, 34)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 51));
        jLabel7.setText("To those who love aviation, the sky is the home..");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(450, 70, 1060, 50);

        jLabel5.setFont(new java.awt.Font("Segoe Script", 3, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 51));
        jLabel5.setText("To most people, the sky is the limit..");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(400, 20, 800, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/china-airlines.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-80, -20, 1520, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        login_home1 add=new login_home1();
        add.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables

}
