import java.sql.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author BeBu
 */
public class searchmflights extends javax.swing.JFrame {

    /**
     * Creates new form searchflights
     */
    public searchmflights() {
        initComponents();
    }
Statement stmt=null;
ResultSet rs =null;
public void setu(String f) {
        txtuser.setText(f);
    }

//public void show1()

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtsrc = new javax.swing.JComboBox();
        txtdes = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFlightInfo = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtdate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        txtuser = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Source");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(48, 35, 33, 14);

        jLabel2.setText("Destination");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(48, 92, 70, 14);

        txtsrc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Banglore(BLR)", "Bhubaneshwar(BBI)", "Delhi(DEL)", "Hyderabad(HYD)" }));
        txtsrc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsrcActionPerformed(evt);
            }
        });
        getContentPane().add(txtsrc);
        txtsrc.setBounds(150, 30, 120, 20);

        txtdes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Banglore(BLR)", "Bhubaneshwar(BBI)", "Delhi(DEL)", "Hyderabad(HYD)" }));
        getContentPane().add(txtdes);
        txtdes.setBounds(148, 89, 120, 20);

        jButton1.setText("search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(95, 195, 65, 23);

        tblFlightInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "FlightCode", "FlightName", "Class", "Source", "Destination", "TotalEco", "TotalBusi", "Date", "Departure", "INR for Economic", "INR for Business"
            }
        ));
        tblFlightInfo.setColumnSelectionAllowed(true);
        tblFlightInfo.setOpaque(false);
        jScrollPane1.setViewportView(tblFlightInfo);
        tblFlightInfo.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 247, 803, 180);

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(48, 130, 34, 14);

        txtdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdateActionPerformed(evt);
            }
        });
        getContentPane().add(txtdate);
        txtdate.setBounds(148, 127, 75, 20);

        jLabel4.setText("yyyy-mm-dd");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(233, 130, 60, 14);
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(450, 30, 140, 20);

        jButton2.setText("book");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(490, 100, 55, 23);
        getContentPane().add(txtuser);
        txtuser.setBounds(680, 170, 70, 20);

        jLabel5.setText("user");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(640, 170, 21, 14);
        getContentPane().add(txtno);
        txtno.setBounds(500, 70, 59, 20);

        jLabel7.setText("no");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(450, 70, 12, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //public void show1()
        String src=(String) txtsrc.getSelectedItem();
             
             String des=(String) txtdes.getSelectedItem();
             String dt=txtdate.getText();
        DefaultTableModel tModel = (DefaultTableModel) tblFlightInfo.getModel();
                int rows = tModel.getRowCount();
                if (rows > 0) {
                    for (int i = 0; i< rows; i++){
                        tModel.removeRow(0);
                    }
                }
       try{

           Class.forName("com.mysql.jdbc.Driver");
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/airlines","root","root");
            stmt=con.createStatement();
           rs=stmt.executeQuery("Select * from Flightdetails");
                    while(rs.next()) {
                       System.out.println(rs.getString(1)+" : "+rs.getString(2));

                String FCode = rs.getString(1);
                String Name=rs.getString(2);
                String cls=rs.getString(3);
                String source=rs.getString(4);
                if(!src.equals(source)) continue;
                String desti=rs.getString(5);
                if(!desti.equals(des)) continue;
                String Eco=rs.getString(6);
                String Busi=rs.getString(7);
                String Date=rs.getString(8);
                if(!Date.equals(dt)) continue;
                String Depart=rs.getString(9);
                String Prceco=rs.getString(10);
                String Prcbui=rs.getString(11);
                tModel.addRow(new Object[] {FCode,Name,cls,source,desti,  Eco,Busi,Date,Depart,Prceco, Prcbui});
                jComboBox1.addItem(FCode);
                    }
                } catch (Exception e){
                    JOptionPane.showMessageDialog(this, e.getMessage());

                }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtsrcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsrcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsrcActionPerformed

    private void txtdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       Statement stmt=null;
    ResultSet rs =null;
    try {
    Class.forName("com.mysql.jdbc.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/airlines","root","root");
    stmt=con.createStatement();
    String fcod=((String) jComboBox1.getSelectedItem());
    rs=stmt.executeQuery("Select * from Flightdetails");
    
    while(rs.next()) {
    String FCode=rs.getString(1);
    System.out.println(FCode);
    if(FCode.equals(fcod)) {
    String as =(rs.getString(6));
    int a=Integer.parseInt(as);
    String bs =(rs.getString(7));
    int b=Integer.parseInt(bs);
    int no=Integer.parseInt(txtno.getText());
    if(no>a+b) {
        JOptionPane.showMessageDialog(null, "Seats Not available");
        break;
    }
        frmAddPassanger add=new frmAddPassanger();
        
        String fcode=(String) jComboBox1.getSelectedItem();
        String src=(String) txtsrc.getSelectedItem();
        String des=(String) txtdes.getSelectedItem();
        add.setu(txtuser.getText());
        String n=txtno.getText();
        add.setno(n);
        add.setf(fcode);
        add.sets(src);
        add.setd(des);
        add.setVisible(true);
        this.setVisible(false);
    }
    }
    }  catch (Exception e){
                    JOptionPane.showMessageDialog(this, e.getMessage());

                }
    
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchmflights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchmflights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchmflights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchmflights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchmflights().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFlightInfo;
    private javax.swing.JTextField txtdate;
    private javax.swing.JComboBox txtdes;
    private javax.swing.JTextField txtno;
    private javax.swing.JComboBox txtsrc;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
