import java.sql.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author BeBu
 */
public class search_flight extends javax.swing.JFrame {

    /**
     * Creates new form search
     */
    public search_flight() {
        initComponents();
    }
Statement stmt=null;
ResultSet rs =null;
public void setu(String f) {
        txtuser.setText(f);
    }

//public void show1()

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtsrc = new javax.swing.JComboBox();
        txtdes = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFlightInfo = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtdate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        txtuser = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel1.setText("Source");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(640, 200, 110, 30);

        jLabel2.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel2.setText("Destination");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(630, 260, 120, 30);

        txtsrc.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        txtsrc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Banglore(BLR)", "Bhubaneshwar(BBI)", "Delhi(DEL)", "Hyderabad(HYD)" }));
        txtsrc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsrcActionPerformed(evt);
            }
        });
        getContentPane().add(txtsrc);
        txtsrc.setBounds(810, 200, 157, 30);

        txtdes.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        txtdes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Banglore(BLR)", "Bhubaneshwar(BBI)", "Delhi(DEL)", "Hyderabad(HYD)" }));
        txtdes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdesActionPerformed(evt);
            }
        });
        getContentPane().add(txtdes);
        txtdes.setBounds(810, 260, 157, 30);

        jButton1.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(910, 380, 77, 25);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setOpaque(false);

        tblFlightInfo.setAutoCreateRowSorter(true);
        tblFlightInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "FlightCode", "FlightName", "Class", "Source", "Destination", "TotalEco", "TotalBusi", "Date", "Departure", "INR for Economic", "INR for Business"
            }
        ));
        tblFlightInfo.setColumnSelectionAllowed(true);
        tblFlightInfo.setGridColor(new java.awt.Color(255, 255, 255));
        tblFlightInfo.setOpaque(false);
        jScrollPane1.setViewportView(tblFlightInfo);
        tblFlightInfo.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(210, 560, 803, 150);

        jLabel3.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel3.setText("Boarding Date");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(630, 330, 150, 21);

        txtdate.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        txtdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdateActionPerformed(evt);
            }
        });
        getContentPane().add(txtdate);
        txtdate.setBounds(810, 330, 120, 23);

        jLabel4.setText("yyyy-mm-dd");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(940, 330, 60, 20);

        jComboBox1.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(1010, 240, 300, 30);

        jButton2.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        jButton2.setText("Book");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(790, 530, 65, 25);

        txtuser.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        txtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserActionPerformed(evt);
            }
        });
        getContentPane().add(txtuser);
        txtuser.setBounds(780, 470, 160, 23);

        jLabel5.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        jLabel5.setText("User");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(680, 470, 60, 20);

        txtfname.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        txtfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtfname);
        txtfname.setBounds(780, 410, 190, 23);

        jLabel6.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        jLabel6.setText("Fname");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(670, 410, 70, 30);

        jLabel8.setFont(new java.awt.Font("Angsana New", 3, 85)); // NOI18N
        jLabel8.setText("LET'S FLY...");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(740, 40, 390, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //public void show1()
        String src=(String) txtsrc.getSelectedItem();
             
             String des=(String) txtdes.getSelectedItem();
             String dt=txtdate.getText();
        DefaultTableModel tModel = (DefaultTableModel) tblFlightInfo.getModel();
                int rows = tModel.getRowCount();
                if (rows > 0) {
                    for (int i = 0; i< rows; i++){
                        tModel.removeRow(0);
                    }
                }
       try{

           Class.forName("com.mysql.jdbc.Driver");
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/airlines","root","root");
            stmt=con.createStatement();
           rs=stmt.executeQuery("Select * from Flightdetails");
                    while(rs.next()) {
                       System.out.println(rs.getString(1)+" : "+rs.getString(2));

                String FCode = rs.getString(1);
                String Name=rs.getString(2);
                String cls=rs.getString(3);
                String source=rs.getString(4);
                if(!src.equals(source)) continue;
                String desti=rs.getString(5);
                if(!desti.equals(des)) continue;
                String Eco=rs.getString(6);
                String Busi=rs.getString(7);
                String Date=rs.getString(8);
                if(!Date.equals(dt)) continue;
                String Depart=rs.getString(9);
                String Prceco=rs.getString(10);
                String Prcbui=rs.getString(11);
                tModel.addRow(new Object[] {FCode,Name,cls,source,desti,  Eco,Busi,Date,Depart,Prceco, Prcbui});
                jComboBox1.addItem(FCode);
                    }
                } catch (Exception e){
                    JOptionPane.showMessageDialog(this, e.getMessage());

                }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtsrcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsrcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsrcActionPerformed

    private void txtdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       frmAddPassanger add=new frmAddPassanger();
        add.setVisible(true);
        String fcode=(String) jComboBox1.getSelectedItem();
        String src=(String) txtsrc.getSelectedItem();
        String des=(String) txtdes.getSelectedItem();
        add.setu(txtuser.getText());
        add.setf(fcode);
        add.sets(src);
        add.setd(des);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfnameActionPerformed

    private void txtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserActionPerformed

    private void txtdesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchmflights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchmflights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchmflights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchmflights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchmflights().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFlightInfo;
    private javax.swing.JTextField txtdate;
    private javax.swing.JComboBox txtdes;
    private javax.swing.JTextField txtfname;
    private javax.swing.JComboBox txtsrc;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
