import java.sql.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author BeBu
 */
public class searchflights extends javax.swing.JFrame {

    /**
     * Creates new form search
     */
    public searchflights() {
        initComponents();
        txtfname.setVisible(false);
        txtuser.setVisible(false);
        jLabel5.setVisible(false);
        jComboBox1.setVisible(false);
        txtno.setVisible(false);
        jLabel10.setVisible(false);
        jLabel6.setVisible(false);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
    }
    public void start() {
        jComboBox1.setVisible(false);
        txtno.setVisible(false);
        jLabel10.setVisible(false);
        jLabel6.setVisible(false);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
    }
    public void c() {
        txtdes.setVisible(false);
        txtsrc.setVisible(false);
        jLabel1.setVisible(false);
        jLabel3.setVisible(false);
        jLabel2.setVisible(false);
        txtdate.setVisible(false);
        jLabel4.setVisible(false);
        jButton1.setVisible(false);
    }
    public void d() {
        txtdes.setVisible(true);
        txtsrc.setVisible(true);
        jLabel1.setVisible(true);
        jLabel3.setVisible(true);
        jLabel2.setVisible(true);
        txtdate.setVisible(true);
        jLabel4.setVisible(true);
        jButton1.setVisible(true);
    }
    public void b() {
        jComboBox1.setVisible(true);
        txtno.setVisible(true);
        jLabel10.setVisible(true);
        jLabel6.setVisible(true);
        jButton2.setVisible(true);
        jButton3.setVisible(true);
    }
Statement stmt=null;
ResultSet rs =null;
public void setu(String f) {
        txtuser.setText(f);
    }

//public void show1()

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtsrc = new javax.swing.JComboBox();
        txtdes = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFlightInfo = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtdate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        txtuser = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtno = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtfname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        home = new javax.swing.JMenu();
        search = new javax.swing.JMenu();
        food = new javax.swing.JMenu();
        about = new javax.swing.JMenu();
        flyers = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        admin = new javax.swing.JMenu();
        exit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setPreferredSize(new java.awt.Dimension(1470, 770));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel1.setText("Source");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 220, 110, 30);

        jLabel2.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel2.setText("Destination");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 280, 120, 30);

        txtsrc.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        txtsrc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsrcActionPerformed(evt);
            }
        });
        getContentPane().add(txtsrc);
        txtsrc.setBounds(250, 220, 157, 30);

        txtdes.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        txtdes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdesActionPerformed(evt);
            }
        });
        getContentPane().add(txtdes);
        txtdes.setBounds(250, 280, 157, 30);

        jButton1.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 0, 255));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(200, 390, 170, 50);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setOpaque(false);

        tblFlightInfo.setAutoCreateRowSorter(true);
        tblFlightInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "FlightCode", "FlightName", "Class", "Source", "Destination", "TotalEco", "TotalBusi", "Date", "Departure", "INR for Economic", "INR for Business"
            }
        ));
        tblFlightInfo.setColumnSelectionAllowed(true);
        tblFlightInfo.setGridColor(new java.awt.Color(255, 255, 255));
        tblFlightInfo.setOpaque(false);
        jScrollPane1.setViewportView(tblFlightInfo);
        tblFlightInfo.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(100, 480, 1020, 180);

        jLabel3.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel3.setText("Boarding Date");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 340, 150, 21);

        txtdate.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        txtdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdateActionPerformed(evt);
            }
        });
        getContentPane().add(txtdate);
        txtdate.setBounds(250, 330, 130, 30);

        jLabel4.setText("(yyyy-mm-dd)");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(390, 340, 100, 20);

        jComboBox1.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(600, 210, 210, 30);

        jButton2.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 255));
        jButton2.setText("Change source, destination or date?");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(460, 410, 380, 30);

        txtuser.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        txtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserActionPerformed(evt);
            }
        });
        getContentPane().add(txtuser);
        txtuser.setBounds(880, 420, 160, 20);

        jLabel10.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        jLabel10.setText("Select flight");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(450, 220, 110, 20);

        jLabel9.setFont(new java.awt.Font("Angsana New", 3, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setText("to us also!!");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(930, 100, 670, 55);

        jLabel5.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        jLabel5.setText("User");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(780, 400, 60, 20);

        txtno.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        txtno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnoActionPerformed(evt);
            }
        });
        getContentPane().add(txtno);
        txtno.setBounds(600, 270, 210, 30);

        jButton4.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 255));
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(1200, 610, 150, 50);

        jButton3.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 255));
        jButton3.setText("Book");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(570, 330, 150, 60);

        txtfname.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        txtfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtfname);
        txtfname.setBounds(890, 360, 210, 30);

        jLabel6.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        jLabel6.setText("Enter no of seats");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(450, 280, 120, 20);

        jLabel8.setFont(new java.awt.Font("Angsana New", 3, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 51, 51));
        jLabel8.setText("Because your time and money is important");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(730, 60, 670, 55);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thy_tr_wp2.jpg"))); // NOI18N
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(-20, -20, 1430, 770);

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setAlignmentX(20.0F);
        jMenuBar1.setPreferredSize(new java.awt.Dimension(301, 51));

        home.setText("HOME");
        home.setAlignmentX(205.0F);
        home.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        home.setIconTextGap(30);
        home.setMaximumSize(new java.awt.Dimension(205, 32767));
        home.setPreferredSize(new java.awt.Dimension(205, 21));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        jMenuBar1.add(home);

        search.setText("SEARCH");
        search.setAlignmentX(205.0F);
        search.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        search.setIconTextGap(30);
        search.setPreferredSize(new java.awt.Dimension(205, 21));
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
        });
        jMenuBar1.add(search);

        food.setText("FOOD MENU");
        food.setAlignmentX(415.0F);
        food.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        food.setIconTextGap(30);
        food.setMaximumSize(new java.awt.Dimension(255, 32767));
        food.setPreferredSize(new java.awt.Dimension(255, 21));
        food.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                foodMouseClicked(evt);
            }
        });
        jMenuBar1.add(food);

        about.setText("ABOUT");
        about.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        about.setIconTextGap(30);
        about.setPreferredSize(new java.awt.Dimension(205, 21));
        about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutMouseClicked(evt);
            }
        });
        jMenuBar1.add(about);

        flyers.setText("FREQUENT FLYERS");
        flyers.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        flyers.setIconTextGap(30);
        flyers.setMaximumSize(new java.awt.Dimension(255, 32767));
        flyers.setPreferredSize(new java.awt.Dimension(255, 21));
        flyers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flyersMouseClicked(evt);
            }
        });
        jMenuBar1.add(flyers);

        jMenu5.setText("EXIT");
        jMenu5.setAlignmentX(280.0F);
        jMenu5.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jMenu5.setIconTextGap(30);
        jMenu5.setMaximumSize(new java.awt.Dimension(0, 0));
        jMenuBar1.add(jMenu5);

        admin.setText("ADMIN");
        admin.setAlignmentX(0.0F);
        admin.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        admin.setIconTextGap(30);
        admin.setMaximumSize(new java.awt.Dimension(175, 32767));
        admin.setPreferredSize(new java.awt.Dimension(175, 21));
        admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminMouseClicked(evt);
            }
        });
        jMenuBar1.add(admin);

        exit.setText("EXIT");
        exit.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        exit.setMaximumSize(new java.awt.Dimension(175, 32767));
        exit.setPreferredSize(new java.awt.Dimension(175, 21));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jMenuBar1.add(exit);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //public void show1()
        String src=(String) txtsrc.getSelectedItem();
             
             String des=(String) txtdes.getSelectedItem();
             String dt=txtdate.getText();
        DefaultTableModel tModel = (DefaultTableModel) tblFlightInfo.getModel();
                int rows = tModel.getRowCount();
                if (rows > 0) {
                    for (int i = 0; i< rows; i++){
                        tModel.removeRow(0);
                    }
                }
       try{
           int count=0;
           Class.forName("com.mysql.jdbc.Driver");
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/airlines","root","root");
            stmt=con.createStatement();
           rs=stmt.executeQuery("Select * from Flightdetails");
                    while(rs.next()) {
                       System.out.println(rs.getString(1)+" : "+rs.getString(2));

                String FCode = rs.getString(1);
                String Name=rs.getString(2);
                String cls=rs.getString(3);
                String source=rs.getString(4);
                if(!src.equals(source)) continue;
                String desti=rs.getString(5);
                if(!desti.equals(des)) continue;
                String Eco=rs.getString(6);
                String Busi=rs.getString(7);
                String Date=rs.getString(8);
                if(!Date.equals(dt)) continue;
                String Depart=rs.getString(9);
                String Prceco=rs.getString(10);
                String Prcbui=rs.getString(11);
                tModel.addRow(new Object[] {FCode,Name,cls,source,desti,  Eco,Busi,Date,Depart,Prceco, Prcbui});
                count++;
                jComboBox1.addItem(FCode);
                    }
                    if(count==0) {
                        System.out.println("no flights");
                        JOptionPane.showMessageDialog(rootPane, "We are sorry..\nWe will try adding it soon.." , "No flight found!!", JOptionPane.INFORMATION_MESSAGE);
                        searchflights add=new searchflights();
        add.setVisible(true);
        add.setu(txtuser.getText());
        this.setVisible(false);
                    } else {
                    b();
                    c();
                    }
                } catch (Exception e){
                    JOptionPane.showMessageDialog(this, e.getMessage());

                }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtsrcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsrcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsrcActionPerformed

    private void txtdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       start();
       d();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfnameActionPerformed

    private void txtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserActionPerformed

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        login_home1 add = new login_home1();
        add.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeMouseClicked

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked
        searchflights1 add = new searchflights1();
        add.setVisible(true);
        this.setVisible(false);// TODO add your handling code here:*/
    }//GEN-LAST:event_searchMouseClicked

    private void foodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodMouseClicked
        foodmenu add = new foodmenu();
        add.setVisible(true);
        this.setVisible(false);
                // TODO add your handling code here:
    }//GEN-LAST:event_foodMouseClicked

    private void aboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMouseClicked
        about add = new about();
        add.setVisible(true);
        this.setVisible(false);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutMouseClicked

    private void flyersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flyersMouseClicked
        login_customer add = new login_customer();
        add.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_flyersMouseClicked

    private void adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseClicked
        login_admin add = new login_admin();
        add.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_adminMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_exitMouseClicked

    private void txtdesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdesActionPerformed

    private void txtnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Statement stmt=null;
    ResultSet rs =null;
    try {
    Class.forName("com.mysql.jdbc.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/airlines","root","root");
    stmt=con.createStatement();
    String fcod=((String) jComboBox1.getSelectedItem());
    rs=stmt.executeQuery("Select * from Flightdetails");
    String sql="Select * from Passenger";
    while(rs.next()) {
    String FCode=rs.getString(1);
    System.out.println(FCode);
    if(FCode.equals(fcod)) {
    String as =(rs.getString(6));
    int a=Integer.parseInt(as);
    String bs =(rs.getString(7));
    int b=Integer.parseInt(bs);
    int no=Integer.parseInt(txtno.getText());
    if(no>a+b) {
        JOptionPane.showMessageDialog(rootPane, "Seats Not available");
        break;
    }
        frmAddPassanger add=new frmAddPassanger();
        
        String fcode=(String) jComboBox1.getSelectedItem();
        String src=(String) txtsrc.getSelectedItem();
        String des=(String) txtdes.getSelectedItem();
        add.setu(txtuser.getText());
        String n=txtno.getText();
        add.setno(n);
        add.setf(fcode);
        add.sets(src);
        add.setd(des);
        rs=stmt.executeQuery(sql);
         int pno=1244;
         while(rs.next())
         {
             pno=rs.getInt(1);
             //System.out.println("Passenger No "+pno);
             pno++;
             //System.out.println("Passenger No"+pno);

         }
         String pn=(""+pno);
         add.setp(pn);
         //con.close();
         //rs.close();
         //stmt.close();
        add.setVisible(true);
        this.setVisible(false);
    }
    }
    }  catch (Exception e){
                    JOptionPane.showMessageDialog(this, e.getMessage());

                }
    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/airlines","root","root");

            String SQL1="Select * from cities ";
            stmt = con.createStatement();
            rs = stmt.executeQuery(SQL1);
            while(rs.next()) {
                
                
                String src=rs.getString(1);
                String des=rs.getString(2);
                txtsrc.addItem(src);
                txtdes.addItem(des);
            }
            
            //con.close();

        } catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());

        }
    }//GEN-LAST:event_formWindowGainedFocus

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         login_customer add=new login_customer();
        add.setVisible(true);
        add.show1();
        
        add.setnme(txtuser.getText());
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchmflights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchmflights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchmflights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchmflights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchmflights().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu about;
    private javax.swing.JMenu admin;
    private javax.swing.JMenu exit;
    private javax.swing.JMenu flyers;
    private javax.swing.JMenu food;
    private javax.swing.JMenu home;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu search;
    private javax.swing.JTable tblFlightInfo;
    private javax.swing.JTextField txtdate;
    private javax.swing.JComboBox txtdes;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtno;
    private javax.swing.JComboBox txtsrc;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
