import java.sql.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class signup_customer extends javax.swing.JFrame {

    /**
     * Creates new form login_customer
     */
    public signup_customer() {
        initComponents();
    }
    Statement stmt=null;
    ResultSet rs =null;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtpass2 = new javax.swing.JPasswordField();
        signup = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtphn = new javax.swing.JTextField();
        txtdob = new javax.swing.JTextField();
        clear = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtmail = new javax.swing.JTextField();
        optfemale = new javax.swing.JRadioButton();
        optmale = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtadd = new javax.swing.JTextArea();
        txtpass1 = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        home = new javax.swing.JMenu();
        search = new javax.swing.JMenu();
        food = new javax.swing.JMenu();
        about = new javax.swing.JMenu();
        flyers = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        admin = new javax.swing.JMenu();
        exit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1470, 770));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Gabriola", 3, 58)); // NOI18N
        jLabel1.setText("LET'S FLY,FLY AWAY...");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(750, 20, 600, 80);

        back.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(750, 600, 90, 30);

        jLabel2.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel2.setText("Confirm Password *");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(380, 450, 190, 40);

        txtpass2.setFont(new java.awt.Font("Georgia", 2, 18)); // NOI18N
        txtpass2.setToolTipText("");
        txtpass2.setName(""); // NOI18N
        txtpass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpass2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtpass2);
        txtpass2.setBounds(630, 450, 210, 30);

        signup.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        signup.setText("Signup");
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        getContentPane().add(signup);
        signup.setBounds(380, 600, 90, 30);

        jLabel5.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel5.setText("Date of Birth");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(380, 230, 140, 40);

        jLabel3.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel3.setText("E-mail Id *");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(380, 350, 170, 40);

        jLabel6.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel6.setText("Your favourite author*");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(380, 550, 230, 40);

        jLabel7.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel7.setText("Create Password *");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(380, 400, 180, 40);

        txtphn.setFont(new java.awt.Font("Georgia", 2, 18)); // NOI18N
        txtphn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphnActionPerformed(evt);
            }
        });
        getContentPane().add(txtphn);
        txtphn.setBounds(630, 500, 210, 30);

        txtdob.setFont(new java.awt.Font("Georgia", 2, 18)); // NOI18N
        txtdob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdobActionPerformed(evt);
            }
        });
        getContentPane().add(txtdob);
        txtdob.setBounds(630, 230, 210, 30);

        clear.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(570, 600, 90, 30);

        jLabel8.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel8.setText("Gender");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(380, 180, 140, 40);

        jLabel10.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel10.setText("Username *");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(380, 130, 140, 40);

        txtname.setFont(new java.awt.Font("Georgia", 2, 18)); // NOI18N
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtname);
        txtname.setBounds(630, 130, 210, 30);

        txtmail.setFont(new java.awt.Font("Georgia", 2, 18)); // NOI18N
        txtmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtmail);
        txtmail.setBounds(630, 350, 210, 30);

        buttonGroup1.add(optfemale);
        optfemale.setFont(new java.awt.Font("Georgia", 2, 18)); // NOI18N
        optfemale.setText("Female");
        getContentPane().add(optfemale);
        optfemale.setBounds(630, 180, 100, 29);

        buttonGroup1.add(optmale);
        optmale.setFont(new java.awt.Font("Georgia", 2, 18)); // NOI18N
        optmale.setText("Male");
        getContentPane().add(optmale);
        optmale.setBounds(750, 180, 80, 29);

        jLabel11.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel11.setText("Address");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(380, 280, 140, 40);

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(166, 32));
        jScrollPane1.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setWheelScrollingEnabled(false);

        txtadd.setColumns(20);
        txtadd.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        txtadd.setRows(2);
        txtadd.setTabSize(5);
        txtadd.setToolTipText("");
        txtadd.setAutoscrolls(false);
        jScrollPane1.setViewportView(txtadd);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(630, 280, 210, 50);

        txtpass1.setFont(new java.awt.Font("Georgia", 2, 18)); // NOI18N
        txtpass1.setToolTipText("");
        txtpass1.setName(""); // NOI18N
        txtpass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpass1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtpass1);
        txtpass1.setBounds(630, 400, 210, 30);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(630, 550, 210, 30);

        jLabel9.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel9.setText("Contact ");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(380, 500, 180, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thy_tr_wp2.jpg"))); // NOI18N
        jLabel4.setText("image");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jLabel4.setMaximumSize(new java.awt.Dimension(1456, 768));
        jLabel4.setMinimumSize(new java.awt.Dimension(1456, 768));
        jLabel4.setPreferredSize(new java.awt.Dimension(1456, 768));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1456, 770);

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setAlignmentX(20.0F);
        jMenuBar1.setPreferredSize(new java.awt.Dimension(301, 51));

        home.setText("HOME");
        home.setAlignmentX(205.0F);
        home.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        home.setIconTextGap(30);
        home.setMaximumSize(new java.awt.Dimension(205, 32767));
        home.setPreferredSize(new java.awt.Dimension(205, 21));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        jMenuBar1.add(home);

        search.setText("SEARCH");
        search.setAlignmentX(205.0F);
        search.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        search.setIconTextGap(30);
        search.setPreferredSize(new java.awt.Dimension(205, 21));
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
        });
        jMenuBar1.add(search);

        food.setText("FOOD MENU");
        food.setAlignmentX(415.0F);
        food.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        food.setIconTextGap(30);
        food.setMaximumSize(new java.awt.Dimension(255, 32767));
        food.setPreferredSize(new java.awt.Dimension(255, 21));
        food.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                foodMouseClicked(evt);
            }
        });
        jMenuBar1.add(food);

        about.setText("ABOUT");
        about.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        about.setIconTextGap(30);
        about.setPreferredSize(new java.awt.Dimension(205, 21));
        about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutMouseClicked(evt);
            }
        });
        jMenuBar1.add(about);

        flyers.setText("FREQUENT FLYERS");
        flyers.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        flyers.setIconTextGap(30);
        flyers.setMaximumSize(new java.awt.Dimension(255, 32767));
        flyers.setPreferredSize(new java.awt.Dimension(255, 21));
        flyers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flyersMouseClicked(evt);
            }
        });
        jMenuBar1.add(flyers);

        jMenu5.setText("EXIT");
        jMenu5.setAlignmentX(280.0F);
        jMenu5.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jMenu5.setIconTextGap(30);
        jMenu5.setMaximumSize(new java.awt.Dimension(0, 0));
        jMenuBar1.add(jMenu5);

        admin.setText("ADMIN");
        admin.setAlignmentX(0.0F);
        admin.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        admin.setIconTextGap(30);
        admin.setMaximumSize(new java.awt.Dimension(175, 32767));
        admin.setPreferredSize(new java.awt.Dimension(175, 21));
        admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminMouseClicked(evt);
            }
        });
        jMenuBar1.add(admin);

        exit.setText("EXIT");
        exit.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        exit.setMaximumSize(new java.awt.Dimension(175, 32767));
        exit.setPreferredSize(new java.awt.Dimension(175, 21));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jMenuBar1.add(exit);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtpass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpass2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpass2ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        login_customer add = new login_customer();
        add.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
        String upSQL1="";
     try {
    Class.forName("com.mysql.jdbc.Driver");
    Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/airlines","root","root");
        Statement stmt1=null;
        ResultSet rs1=null;
        stmt=con.createStatement();
         rs=stmt.executeQuery("select * from customer");
         String sex="";
             
             String name=txtname.getText();
             
             if(optfemale.isSelected()) {sex="Female";}
             else if(optmale.isSelected()) {sex="Male";}
             String dob=txtdob.getText();
             String adrss=txtadd.getText();
             String eid=txtmail.getText();
             char[] pass1=txtpass1.getPassword();
             String pwd1 = String.copyValueOf(pass1);
             char[] pass2=txtpass2.getPassword();
             String pwd2 = String.copyValueOf(pass2);
             String que=jTextField1.getText();
             String phn=txtphn.getText();
             if(name.length()==0)  // Checking for empty field
      JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up all fields");
   else if(pwd1.length()==0)  // Checking for empty field
      JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up all fields");
             else if(pwd2.length()==0)  // Checking for empty field
      JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up all fields");
             else if(eid.length()==0)  // Checking for empty field
      JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up all fields");
             else if(!pwd1.equals(pwd2))
                 JOptionPane.showMessageDialog(null, "Passwords do not match!!");
             else {
 System.out.println("INSERT INTO customer VALUES ('"+(name)+"','"+(sex)+"','"+(dob)+"','"+(adrss)+"','"+(eid)+"','" +(pwd1)+"','"+(phn)+"')");
 String strSQL="INSERT INTO customer VALUES ('"+(name)+"','"+(sex)+"','"+(dob)+"','"+(adrss)+"','"+(eid)+"','" +(pwd1)+"','"+(phn)+"','"+(que)+"')";
 int rowEffected=stmt.executeUpdate(strSQL);
          // System.out.println("rows Effected :"+rowEffected);
          //   System.out.println(strSQL);
           JOptionPane.showMessageDialog(this, "You are now part of FlightSite", "Congratulations",JOptionPane.INFORMATION_MESSAGE);
    /**********update flight seat***********/
                 stmt1 = con.createStatement();
                rs1 = stmt1.executeQuery("select * from custlogin");

                 
                
                
                
                   upSQL1="insert into custlogin values('"+(name)+"','"+(pwd1)+"')";
                
            System.out.println(upSQL1);
            int rowsEffected1=stmt1.executeUpdate(upSQL1);
            
                //JOptionPane.showMessageDialog(this,"Product Record Updated");
           // System.out.println(rowsEffected1+"rows effected");
            /* 
            login_customer sig = new login_customer();
            sig.signlogin(name,pwd1);
            
            */
            login_customer add = new login_customer();
           
        add.setVisible(true);
        add.signlogin(txtname.getText());
        this.setVisible(false); 
            } 
            txtadd.setText("");
       txtname.setText("");
       txtphn.setText("");
       txtmail.setText("");
       txtpass1.setText("");
       txtpass2.setText("");
       txtdob.setText("");
       optfemale.setSelected(true);
       optmale.setSelected(true);
     }
    catch(Exception e)
    {
JOptionPane.showMessageDialog(this, e.getMessage());
e.printStackTrace();
    }                                       

    }//GEN-LAST:event_signupActionPerformed

    private void txtphnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphnActionPerformed

    private void txtdobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdobActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
       txtadd.setText("");
       txtname.setText("");
       txtphn.setText("");
       txtmail.setText("");
       txtpass1.setText("");
       txtpass2.setText("");
       txtdob.setText("");
       optfemale.setSelected(true);
       optmale.setSelected(true);
    }//GEN-LAST:event_clearActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmailActionPerformed

    private void txtpass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpass1ActionPerformed

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        login_home1 add = new login_home1();
        add.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeMouseClicked

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked
        searchflights1 add = new searchflights1();
        add.setVisible(true);
        this.setVisible(false);// TODO add your handling code here:*/
    }//GEN-LAST:event_searchMouseClicked

    private void foodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodMouseClicked
        foodmenu add = new foodmenu();
        add.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_foodMouseClicked

    private void aboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMouseClicked
        about add = new about();
        add.setVisible(true);
        this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_aboutMouseClicked

    private void flyersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flyersMouseClicked
        login_customer add = new login_customer();
        add.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_flyersMouseClicked

    private void adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseClicked
        login_admin add = new login_admin();
        add.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_adminMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_exitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup_customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu about;
    private javax.swing.JMenu admin;
    private javax.swing.JButton back;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clear;
    private javax.swing.JMenu exit;
    private javax.swing.JMenu flyers;
    private javax.swing.JMenu food;
    private javax.swing.JMenu home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton optfemale;
    private javax.swing.JRadioButton optmale;
    private javax.swing.JMenu search;
    private javax.swing.JButton signup;
    private javax.swing.JTextArea txtadd;
    private javax.swing.JTextField txtdob;
    private javax.swing.JTextField txtmail;
    private javax.swing.JTextField txtname;
    private javax.swing.JPasswordField txtpass1;
    private javax.swing.JPasswordField txtpass2;
    private javax.swing.JTextField txtphn;
    // End of variables declaration//GEN-END:variables
}
