import java.sql.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class viewstatus extends javax.swing.JFrame {

    /**
     * Creates new form login_customer
     */
    public viewstatus() {
        initComponents();
    }
    Statement stmt=null;
    //Statement stmt1=null;
    ResultSet rs =null;
    public void setu(String user) {
        txtname.setText(user);
    }
    public void setad(String user) {
        txtadd.setText(user);
    }
    public void setc(String user) {
        txtphn.setText(user);
    }
    public void setg(String user) {
        jLabel14.setText(user);
    }
    public void setd(String user) {
        txtdob.setText(user);
    }
    public void sete(String user) {
        txtmail.setText(user);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        back = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtdob = new javax.swing.JLabel();
        txtmail = new javax.swing.JLabel();
        txtphn = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtname = new javax.swing.JLabel();
        txtadd = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFlightInfo = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        home = new javax.swing.JMenu();
        search = new javax.swing.JMenu();
        food = new javax.swing.JMenu();
        about = new javax.swing.JMenu();
        flyers = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        admin = new javax.swing.JMenu();
        exit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1470, 770));
        getContentPane().setLayout(null);

        back.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(570, 600, 110, 40);

        jLabel5.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 51));
        jLabel5.setText("Date of Birth");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(210, 160, 140, 60);

        jLabel3.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3.setText("E-mail Id *");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(720, 160, 140, 60);

        jLabel6.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 51));
        jLabel6.setText("Contact ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(720, 210, 180, 60);

        jLabel8.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 51));
        jLabel8.setText("Gender");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(720, 110, 140, 60);

        jLabel10.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 51));
        jLabel10.setText("Username *");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(210, 110, 140, 60);

        jLabel11.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 51));
        jLabel11.setText("Address");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(210, 210, 140, 60);

        jLabel9.setFont(new java.awt.Font("Gabriola", 3, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 255, 51));
        jLabel9.setText("We are always here to help you..");
        jLabel9.setToolTipText("");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(350, 30, 500, 50);

        txtdob.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        txtdob.setForeground(new java.awt.Color(255, 255, 51));
        txtdob.setText("Date of Birth");
        getContentPane().add(txtdob);
        txtdob.setBounds(430, 160, 170, 60);

        txtmail.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        txtmail.setForeground(new java.awt.Color(255, 255, 51));
        txtmail.setText("E-mail Id *");
        getContentPane().add(txtmail);
        txtmail.setBounds(940, 170, 240, 30);

        txtphn.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        txtphn.setForeground(new java.awt.Color(255, 255, 51));
        txtphn.setText("Contact ");
        getContentPane().add(txtphn);
        txtphn.setBounds(940, 210, 210, 60);

        jLabel14.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 51));
        jLabel14.setText("Gender");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(940, 110, 140, 60);

        jButton1.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        jButton1.setText("Click here to view booking history");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(410, 280, 540, 40);

        txtname.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        txtname.setForeground(new java.awt.Color(255, 255, 51));
        txtname.setText("Username *");
        getContentPane().add(txtname);
        txtname.setBounds(430, 110, 170, 60);

        txtadd.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        txtadd.setForeground(new java.awt.Color(255, 255, 51));
        txtadd.setText("Address");
        getContentPane().add(txtadd);
        txtadd.setBounds(430, 220, 250, 30);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setOpaque(false);

        tblFlightInfo.setAutoCreateRowSorter(true);
        tblFlightInfo.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        tblFlightInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Passenger Code", "Passenger Name", "FlightCode", "FlightName", "Class", "Source", "Destination", "Date", "Departure", "Email ID", "INR", "Seat No"
            }
        ));
        tblFlightInfo.setColumnSelectionAllowed(true);
        tblFlightInfo.setGridColor(new java.awt.Color(255, 255, 255));
        tblFlightInfo.setOpaque(false);
        tblFlightInfo.setRowHeight(30);
        jScrollPane1.setViewportView(tblFlightInfo);
        tblFlightInfo.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 360, 1230, 180);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/china-airlines.jpg"))); // NOI18N
        jLabel4.setText("image");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jLabel4.setMaximumSize(new java.awt.Dimension(1456, 768));
        jLabel4.setMinimumSize(new java.awt.Dimension(1456, 768));
        jLabel4.setPreferredSize(new java.awt.Dimension(1456, 768));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1456, 770);

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setAlignmentX(20.0F);
        jMenuBar1.setPreferredSize(new java.awt.Dimension(301, 51));

        home.setText("HOME");
        home.setAlignmentX(205.0F);
        home.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        home.setIconTextGap(30);
        home.setMaximumSize(new java.awt.Dimension(205, 32767));
        home.setPreferredSize(new java.awt.Dimension(205, 21));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        jMenuBar1.add(home);

        search.setText("SEARCH");
        search.setAlignmentX(205.0F);
        search.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        search.setIconTextGap(30);
        search.setPreferredSize(new java.awt.Dimension(205, 21));
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
        });
        jMenuBar1.add(search);

        food.setText("FOOD MENU");
        food.setAlignmentX(415.0F);
        food.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        food.setIconTextGap(30);
        food.setMaximumSize(new java.awt.Dimension(255, 32767));
        food.setPreferredSize(new java.awt.Dimension(255, 21));
        food.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                foodMouseClicked(evt);
            }
        });
        jMenuBar1.add(food);

        about.setText("ABOUT");
        about.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        about.setIconTextGap(30);
        about.setPreferredSize(new java.awt.Dimension(205, 21));
        about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutMouseClicked(evt);
            }
        });
        jMenuBar1.add(about);

        flyers.setText("FREQUENT FLYERS");
        flyers.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        flyers.setIconTextGap(30);
        flyers.setMaximumSize(new java.awt.Dimension(255, 32767));
        flyers.setPreferredSize(new java.awt.Dimension(255, 21));
        flyers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flyersMouseClicked(evt);
            }
        });
        jMenuBar1.add(flyers);

        jMenu5.setText("EXIT");
        jMenu5.setAlignmentX(280.0F);
        jMenu5.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jMenu5.setIconTextGap(30);
        jMenu5.setMaximumSize(new java.awt.Dimension(0, 0));
        jMenuBar1.add(jMenu5);

        admin.setText("ADMIN");
        admin.setAlignmentX(0.0F);
        admin.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        admin.setIconTextGap(30);
        admin.setMaximumSize(new java.awt.Dimension(175, 32767));
        admin.setPreferredSize(new java.awt.Dimension(175, 21));
        admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminMouseClicked(evt);
            }
        });
        jMenuBar1.add(admin);

        exit.setText("EXIT");
        exit.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        exit.setMaximumSize(new java.awt.Dimension(175, 32767));
        exit.setPreferredSize(new java.awt.Dimension(175, 21));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jMenuBar1.add(exit);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
       login_customer add=new login_customer();
        add.setVisible(true);
        add.show1();
        add.setnme(txtname.getText());
        this.setVisible(false);
        
        /*if(txtname.getText().length()==0)  // Checking for empty field
      JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up all fields");
   else if(txtpass.getPassword().length==0)  // Checking for empty field
      JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up all fields");
   else{
       String user = txtname.getText();   // Collecting the input
       char[] pass = txtpass.getPassword(); // Collecting the input
       String pwd = String.copyValueOf(pass);  // converting from array to string
       if(validate_login(user,pwd)) {
          //JOptionPane.showMessageDialog(null, "Correct Login Credentials");
          jButton1.setVisible(false);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
        user.setVisible(false);
        jLabel2.setVisible(false);
        jLabel5.setVisible(false);
        txtname.setVisible(false);
        txtpass.setVisible(false);
        jButton4.setVisible(true);
        jButton5.setVisible(true);
        jButton6.setVisible(true);
        jButton7.setVisible(true);
        jButton9.setVisible(true);
        txtdob.setVisible(true);
        jLabel6.setVisible(true);
       }
       else {
          JOptionPane.showMessageDialog(null, "Incorrect Login Credentials");
          txtname.setText("");
          txtpass.setText("");
       }
        */
    }//GEN-LAST:event_backActionPerformed

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        login_home1 add = new login_home1();
        add.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeMouseClicked

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked
        searchflights add = new searchflights();
        add.setVisible(true);
        this.setVisible(false);// TODO add your handling code here:*/
    }//GEN-LAST:event_searchMouseClicked

    private void foodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodMouseClicked
        foodmenu add = new foodmenu();
        add.setVisible(true);
        this.setVisible(false);
                // TODO add your handling code here:
    }//GEN-LAST:event_foodMouseClicked

    private void aboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMouseClicked
        about add = new about();
        add.setVisible(true);
        this.setVisible(false);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutMouseClicked

    private void flyersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flyersMouseClicked
        login_customer add = new login_customer();
        add.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_flyersMouseClicked

    private void adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseClicked
        login_admin add = new login_admin();
        add.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_adminMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_exitMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //String src=(String) txtsrc.getSelectedItem();
             
             //String des=(String) txtdes.getSelectedItem();
             String user=txtname.getText();
        DefaultTableModel tModel = (DefaultTableModel) tblFlightInfo.getModel();
                int rows = tModel.getRowCount();
                if (rows > 0) {
                    for (int i = 0; i< rows; i++){
                        tModel.removeRow(0);
                    }
                }
       try{
           int count=0;
           Class.forName("com.mysql.jdbc.Driver");
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/airlines","root","root");
            stmt=con.createStatement();
            String s2="Select custdetails.passno,custdetails.nme,custdetails.flightcode,custdetails.flightname,custdetails.class,custdetails.src,custdetails.des,flightdetails.fdate,flightdetails.ftime,custdetails.email,flightdetails.prceco,flightdetails.prcbui,custdetails.seatno from custdetails,flightdetails where custdetails.flightcode=flightdetails.flightcode && custdetails.username='"+(user)+"'";
                //rs2=stmt.executeQuery(s1);
           rs=stmt.executeQuery(s2);
           //ResultSet rs2=null;
                    while(rs.next()) {
                       //System.out.println(rs.getString(1)+" : "+rs.getString(2));

                String pCode = rs.getString(1);
                String Name=rs.getString(2);
                String fName=rs.getString(4);
                String fCode = rs.getString(3);
                String cls=rs.getString(5);
                String source=rs.getString(6);
                //if(!src.equals(source)) continue;
                String desti=rs.getString(7);
                //if(!desti.equals(des)) continue;
                //String Eco=rs.getString(6);
                String sta=rs.getString(4);
               // String Date=rs.getString(8);
                //if(!Date.equals(dt)) continue;
                String eid=rs.getString(10);
                //String Prceco=rs.getString(11);
               // String Prcbui=rs.getString(12);
                String seatno=rs.getString(13);
                //String s1="Select * from flightdetails where flightcode='"+(fCode)+"'";
                String Date=rs.getString(8);
                String Depart=rs.getString(9);
                String Prce="";
                //rs2=stmt1.executeQuery(s1);
                //while(rs2.next()) {
                    
                if(cls.equals("Busi"))
                    Prce=rs.getString(12);
                else Prce=rs.getString(11);
                //}
                tModel.addRow(new Object[] {pCode,Name,fCode,fName,cls,source,desti,Date,Depart,eid,Prce, seatno});
                count++;
                /*jComboBox1.addItem(FCode);
                    }
                    if(count==0) {
                        System.out.println("no flights");
                        JOptionPane.showMessageDialog(rootPane, "We are sorry..\nWe will try adding it soon.." , "No flight found!!", JOptionPane.INFORMATION_MESSAGE);
                        
                    } else {
                    b();
                    c();
                    }*/
                    }
                    if(count==0) {
                        JOptionPane.showMessageDialog(rootPane, "You haven't booked any flight yet!","No history found",JOptionPane.INFORMATION_MESSAGE);
                    }
                } catch (Exception e){
                    JOptionPane.showMessageDialog(this, e.getMessage());

                }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup_customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu about;
    private javax.swing.JMenu admin;
    private javax.swing.JButton back;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenu exit;
    private javax.swing.JMenu flyers;
    private javax.swing.JMenu food;
    private javax.swing.JMenu home;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu search;
    private javax.swing.JTable tblFlightInfo;
    private javax.swing.JLabel txtadd;
    private javax.swing.JLabel txtdob;
    private javax.swing.JLabel txtmail;
    private javax.swing.JLabel txtname;
    private javax.swing.JLabel txtphn;
    // End of variables declaration//GEN-END:variables
}
